### ISSUE TITLE
Pregunta 3 Control 1

### ISSUE THREAD

**Issue by cristobalba** [IIC2413/Syllabus-2022-1#10]
Hola, en esta pregunta quería saber si "capitanId" en Buques es igual a "personalId" en Personal?, en caso de que el capitan este registrado en Personal. Y mi segunda duda es si el resultado de la consulta debe ser solo los Id's de los capitanes no registrados en Personal?

Muchas gracias

![image](https://user-images.githubusercontent.com/80768909/159372693-129afca7-b5a5-4fce-8c25-635cc67e45ec.png)

![159348598-140974ad-952b-4329-a9f5-8d4977689be7](https://user-images.githubusercontent.com/80768909/159372615-094f734b-9170-4170-a109-a00cbf3ea531.png)

**Comment by matiastoro** [comment]
capitanId de tabla Buques referencia a personalId de tabla Personal.
Debes devolver los ids, porque si no estan registrados no tienes como obtener su nombre.
