### ISSUE TITLE
Visualización de nuestra página web

### ISSUE THREAD

**Issue by gitlobo** [IIC2413/Syllabus-2022-1#100]
Holaa :), qué ruta ocupamos para poder ver nuestra página web desde el servidor en nuestro navegador? Graciaaaas.

**Comment by Daniel-SebastianGaete** [comment]
Con su archivo `index.php` en la carpeta Sites, la ruta es `codd.ing.puc.cl/~grupoXX/index.php?`.
Saludos

**Comment by gitlobo** [comment]
AYYYY ya nos funcionooooooo, nos falta el "~" muchas graciassss!!!! <3<3<3<3<3
