### ISSUE TITLE
gitignore repositorio curso

### ISSUE THREAD

**Issue by diegocostares** [IIC2413/Syllabus-2022-1#103]
Hola, tengo cargado el repositorio del curso en mi computador, pero como no tienen agregado en el gitignore el '.DS_Store' y el '.vscode' (que siempre se generan en mi pc XD), me surgen conflictos cada vez que hago pull. ¿Podrían incluirlo en el gitignore para no tener más problemas? 😥

**Comment by arpincheira** [comment]
Añadido
