### ISSUE TITLE
Consulta 5, Control 2

### ISSUE THREAD

**Issue by lfb1206** [IIC2413/Syllabus-2022-1#104]
¿En esta consulta que se debe entregar? ¿El nombre del usuario con la mayor compra, los nombres de los usuarios ordenados por su mayor compra, la mayor compra de cada usuario o alguna otra combinación?

Muchas gracias

**Comment by ebenstom** [comment]
Tengo la misma duda

**Comment by nicoabarca** [comment]
Igual tengo la misma duda

**Comment by Dafnemami** [comment]
Me sumo a la duda, el enunciado no es claro

**Comment by diegocostares** [comment]
Con respecto a la misma pregunta, no me queda claro si "la compra con mayor valor" corresponde al total de la compra por usuario o al producto de mayor valor comprado por un usuario.

**Comment by Piolawa** [comment]
Tengo la misma duda

**Comment by TonioElbuey** [comment]
+ 1

**Comment by vicentethomas** [comment]
up

**Comment by andres-tamm** [comment]
Hola!
Lo que se pide es el nombre del usuario (o _los usuarios_, en caso de que haya empate) que realizó la compra con el mayor valor, independiente de tienda o producto. 

Espero quede más claro.

**Comment by carmebe** [comment]
Hola, con respecto al valor de la compra, ¿a qué se refiere? ¿Se refiere a la cantidad más alta de contenido de compra, el precio total más alto (suma de todos los precios de los productos * sus cantidades), u otra cosa?

**Comment by Dafnemami** [comment]
Me sumo a la duda anterior, cuando dices "compra" se refiere a todo lo asociado a un único cid en un sentido de dinero total pagado?

**Comment by andres-tamm** [comment]
¡Hola @carmebe , @Dafnemami!

_Compra_ se refiere al **dinero total pagado**.
Suma de: los precios de los productos * sus cantidades. 

Es como _"el total de la boleta"_

Espero haya quedado más claro!
