### ISSUE TITLE
[Control 2] Consulta 10

### ISSUE THREAD

**Issue by aurmeneta** [IIC2413/Syllabus-2022-1#105]
Hola!

¿En la consulta 10 hay que considerar solo las compras con 3 o más productos distintos? Es decir, ¿si una compra tiene solo un producto pero tres unidades de éste, no cuenta?

Gracias!

**Comment by Gau04** [comment]
Tengo la misma duda para esta consulta

**Comment by andres-tamm** [comment]
Hola!
Tal como dice el enunciado "Si un producto fue comprado dos o más veces, hay que contar esto" es decir que si tengo 3 o más unidades de un mismo producto se considera como que efectivamente tengo 3 o más productos
