### ISSUE TITLE
Problemas al correr control 2

### ISSUE THREAD

**Issue by AgustinAraya** [IIC2413/Syllabus-2022-1#106]
Hola, al correr el control 2, me salen una serie de errores y por lo tanto no puedo probar mis consultas.  Muestro pantallasos de la secuencia a continucación:
Input:
<img width="1007" alt="Captura de Pantalla 2022-04-25 a la(s) 14 52 14" src="https://user-images.githubusercontent.com/89549252/165154846-727ef58d-577a-47a4-950b-0c933150dfb5.png">
Output:
<img width="1095" alt="Captura de Pantalla 2022-04-25 a la(s) 14 48 50" src="https://user-images.githubusercontent.com/89549252/165154527-c50a03f1-591e-46cf-9dfe-80e8f9f7e696.png">
<img width="1087" alt="Captura de Pantalla 2022-04-25 a la(s) 14 48 59" src="https://user-images.githubusercontent.com/89549252/165154541-0a37a1d6-a1fd-4441-a87f-2eb3c17e97f5.png">
<img width="1087" alt="Captura de Pantalla 2022-04-25 a la(s) 14 49 07" src="https://user-images.githubusercontent.com/89549252/165154553-b2a9115d-18d1-481c-8b6f-38c5a1fe9002.png">
<img width="1086" alt="Captura de Pantalla 2022-04-25 a la(s) 14 49 14" src="https://user-images.githubusercontent.com/89549252/165154563-eece905c-fd70-4dff-905f-ff3cb09f5fd4.png">
<img width="1079" alt="Captura de Pantalla 2022-04-25 a la(s) 14 49 23" src="https://user-images.githubusercontent.com/89549252/165154578-c996d733-f9b2-4179-bcbe-1c9cdde40cbf.png">
<img width="1002" alt="Captura de Pantalla 2022-04-25 a la(s) 14 49 31" src="https://user-images.githubusercontent.com/89549252/165154584-a7d1c9ae-18ea-45d5-9d3a-ae3755653982.png">

**Comment by jerrymendoza** [comment]
Hola @AgustinAraya ! 
Prueba corriendo el notebook en [colab](https://colab.research.google.com).
