### ISSUE TITLE
[Control 2] Pregunta 7

### ISSUE THREAD

**Issue by ebenstom** [IIC2413/Syllabus-2022-1#107]
Nos piden nombre de los usuarios que compraron uno de los cinco productos más caros. Hasta ahora tengo una lista de personas con al lado el producto que compraron (se repiten los nombres si compraron mas de un producto de los 5 más caros), pero no se si es exacto lo que piden o debería dar sólo una lista con los nombres sin repetir independiente del producto que compraron.

**Comment by ignaciaurrutia** [comment]
Me sumo a esta pregunta. También me entró la duda de si la lista debe ser de **todas** las personas que compraron los 5 productos más caros de todos los productos, o los 5 más caros de los que se compraron. Por ejemplo, tenemos que los 5 productos más caros son Notebook, Refrigerador, Pelota de Futbol, Monitor y Cafetera; digamos que 3 personas compraron un notebook y después 2 personas compraron una mancuerna, y 2 una polera de BTS. Debemos entregar una lista con las primeras 3 personas solamente porque compraron uno de los 5 productos más caros de todos, o una lista con los que compraron las mancuernas también, no se encuentren en el top 5 de las compras pero no del top 5 de productos. Por otro lado, qué pasa si 7 personas compran una cafetera, ¿Se entrega la lista con 7 personas?  Gracias de antemano.

**Comment by andres-tamm** [comment]
Hola!
Lo correcto es entregar una lista con nombres de todos los usuarios que han comprado alguno de los 5 productos más caros. Si un usuario compró más de alguno de estos 5 productos, debe aparecer solo una vez.
