### ISSUE TITLE
Control 2, consulta 12

### ISSUE THREAD

**Issue by lfb1206** [IIC2413/Syllabus-2022-1#108]
En el caso que dos o mas tiendas empaten para el primer lugar ¿Hay que listar todas las tiendas o las empatadas?
Este issue es para evitar asumir cierto requisito de la consulta.

**Comment by andres-tamm** [comment]
Hola! 
En caso de que dos o más tiendas empaten para el primer lugar, debes listar **todas las que empaten**.
