### ISSUE TITLE
Control 2, Consulta 7

### ISSUE THREAD

**Issue by Dafnemami** [IIC2413/Syllabus-2022-1#109]
Por cada producto, de los 5 más caros, logro obtener **una** persona que lo ha comprado. Mi problema (creo, pues estoy suponiendo que hay más de una persona por producto) es que no logro visualizar si existe más de una persona.  Mi sospecha del error:

En todas mis intentos de consulta tengo: `SELECT usuarios.nombre, productos.nombre`

Lo cual me fuerza después, por algo que no entiendo muy bien aún, a poner **ambos** atributos en GROUP BY.  Pienso que el poner ambos puede ocultar resultados de interés.

Yo busco la posibilidad de tener solamente:  `GROUP BY productos.nombre`, para dar justamente el espacio a que aparezca más de un usuario, pero no logro dar con una consulta, usando LIMIT que me lo permita.

**Comment by andres-tamm** [comment]
Hola! No me queda muy claro cual es tu duda.

Lo que se pide es que primero obtengas los 5 productos más caros y luego encuentres el nombre de los usuarios que han comprado alguno de esos productos. 

Quedo atento por si aun sigues con dudas!

**Comment by Dafnemami** [comment]
Mi problema es que tengo una persona por producto, y no logro ver si hay más de una por producto. Pero no sé si es porque efectivamente ese es el resultado o mi consulta no es correcta. Se entiende mejor ahí?

**Comment by andres-tamm** [comment]
¡Hola @Dafnemami ! 
No puedo darte información con respecto al resultado! 

Pero para tu tranquilidad, si crees que tu consulta no considera el hecho de que pueden haber más personas que hayan comprado algún producto del _"top 5 más caro"_, puedes hacer una prueba agregando más datos a las tablas. Podrías agregar una celda para agregar datos extra. Luego al momento de la entrega, simplemente eliminas la celda que agregaste y ejecutas la celda que llena las tablas nuevamente.

Espero que esto te ayude!
