### ISSUE TITLE
Control 1 - Pregunta 2

### ISSUE THREAD

**Issue by ignaciaurrutia** [IIC2413/Syllabus-2022-1#11]
Hola, hay un pequeño error de tipeo en la pregunta 2, nos piden "Lagos del Sur", pero en el ejemplo de la otra página sale "Lagos de Sur". ¿Cuál usamos? Entiendo que se referían a lo mismo, y tal vez no importa en este caso, pero cuando tengamos que programar es importante que sean iguales así que me pareció que valía la pena comentarlo.

**Comment by matiastoro** [comment]
Usen la que dice el enunciado. Lo que sale en la 2 es un ejemplo de instancias.

**Comment by Mario-uc** [comment]
Una consulta , en Personal , el primer atributo dice "peronalId". ¿Deberiamos dejarlo así o cambiarlo por "personalId"?
