### ISSUE TITLE
[Control 2] Consulta 12

### ISSUE THREAD

**Issue by tamyhan** [IIC2413/Syllabus-2022-1#111]
Hola! En esta pregunta, hay que hacer una consulta por región? Si es que no es así, en caso de empate, se debe mostrar la región más de una vez en la tabla con las tiendas correspondientes en la otra columna?

**Comment by andres-tamm** [comment]
Hola! 
Efectivamente en caso de empate, debes mostrar la región más de una vez en la tabla, con las tiendas correspondientes.
