### ISSUE TITLE
[Control 2] Consulta 7

### ISSUE THREAD

**Issue by JorgeGuzz** [IIC2413/Syllabus-2022-1#112]
**Enunciado**: "Nombre de los usuarios que compraron **uno** de los cinco productos más caros. Para sacar los cinco más caros, usar LIMIT:"

Holaa, en esta pregunta se refieren a al menos uno de los cinco productos más caros, o a exactamente uno de estos.

**Comment by andres-tamm** [comment]
Hola!
Lo correcto es entregar una lista con nombres de todos los usuarios que han comprado **alguno** de los 5 productos más caros. Si un usuario compró más de alguno de estos 5 productos, debe aparecer **solo una vez.**

Issue equivalente a #107
