### ISSUE TITLE
[Control 2] Duda atributo "Nombre"

### ISSUE THREAD

**Issue by TonioElbuey** [IIC2413/Syllabus-2022-1#113]
Hola,

En varias consultas se pide que se muestren los nombres de los "Usuarios" pero el nombre no es único. Puede haber dos personas con el mismo nombre. Entonces, ¿no deberíamos pedir el nombre y el id de las personas en su lugar?

**Comment by andres-tamm** [comment]
Hola! 
Exactamente, un dato que no es primary key no puede asumirse **único**. Mostrar el nombre junto con el id es una buena forma de asegurarse de que no estas omitiendo datos!

**Comment by larryuc** [comment]
Entonces se recomienda mostrar el UID además del nombre cuando piden solo el Nombre en la pregunta?
