### ISSUE TITLE
[Control 2] Pregunta 11

### ISSUE THREAD

**Issue by gitlobo** [IIC2413/Syllabus-2022-1#114]
Hola! No entiendo esta parte de la pregunta "al menos un producto más caro que el producto más barato que existe en todos los productos", me la podrían explicar en otras palabras?
Graciasss

**Comment by andres-tamm** [comment]
Hola!
Lo que piden es el id de las tiendas que vendan al menos un producto más caro, que el producto más barato de todos los productos que existen (toda la tabla productos).

Quedo atento por si sigues con la duda!

**Comment by isufan** [comment]
@gitlobo asumo que también se podría explicar como "los id de las tiendas que vendan al menos un producto que no sea el producto más barato que existe" si no estoy mal.
