### ISSUE TITLE
Duda sql: Uso de distinct

### ISSUE THREAD

**Issue by Dafnemami** [IIC2413/Syllabus-2022-1#115]
Veo que hacer: "DISTINCT a,b" ó "DISTINCT(a,b)" arroja el mismo resultado cuando la tabla posee dos tuplas (a,b) iguales, que es lo que espero. Pero cuando la tabla posee (a,b1) y (a,b2), "DISTINCT a,b" me entrega **ambas** tuplas, al igual que "DISTINCT (a,b)" 

No debiera "DISTINCT a,b"  eliminar (a,b1) ó (a,b2) al tener un duplicado para "a"?

Cuál sería la diferencia entonces entre "DISTINCT a,b" y "DISTINCT(a,b)" ?

**Comment by andres-tamm** [comment]
Hola! 
La sintaxis de DISTINCT es `SELECT DISTINCT a,b,c FROM ....` el uso de paréntesis no afecta la lógica de la consulta.

Además, al usar DISTINCT para múltiples columnas (a, b, c, etc.) va a retornar aquellas tuplas (filas de la tabla) que sean distintas entre sí, es decir si la tabla posee (a,b1) y (a,b2), DISTINCT retornará ambas tuplas, dado que, la tuplas como un todo, son distintas.

Espero te halla quedado más claro! En caso contrario no dudes en preguntar.
