### ISSUE TITLE
[Control 2] Consulta para hacer un producto cruz a partir de otra consulta

### ISSUE THREAD

**Issue by EnzoMorata** [IIC2413/Syllabus-2022-1#116]
Estoy interesado en realizar un producto cruz consigo misma para una consulta previa; pero tengo el problema que, si bien puedo guardar una consulta anidada en un alias, no sé como podria hacer para guardarla a su vez en otro alias sin que de un error. Entonces, quería consultar que puedo hacer en este caso o si es posible crear tablas con consultas que hagamos en el control, para realizar esto.

**Comment by andres-tamm** [comment]
Hola! 
No es posible guardar una consulta en múltiples alias. 
Podrías cambiar la lógica de tus consulta y ver si puedes plantearlo de otra forma, o bien, podrias hacer la misma consulta 2 veces y la guardarla con un alias distinto cada vez, para luego hacer _"el producto cruz"_.

Saludos!
