### ISSUE TITLE
[Control 2] Uso de WITH

### ISSUE THREAD

**Issue by carmebe** [IIC2413/Syllabus-2022-1#117]
Hola, quería saber si está permitido usar WITH para definir tablas que luego usaremos varias veces (similar a la función Rho en álgebra relacional). El asunto es que en algunas consultas tuve que realizar consultas anidadas repetidas, y para ahorrar espacio y evitar líneas de mas usé este método.

Por si acaso, vi que WITH se usó en las pautas de controles de semestres anteriores, no sé si este será la excepción.

**Comment by andres-tamm** [comment]
Hola!
Si está permitido utilizar `WITH`.

Saludos!
