### ISSUE TITLE
Duda uso de jupyter

### ISSUE THREAD

**Issue by arturoprietovic** [IIC2413/Syllabus-2022-1#119]
Hola. No logro hacer funcionar jupyter notebook (en vscode ni en chrome) para probar mis respuestas del control 2. Al correr el notebook me sale lo siguiente:
![image](https://user-images.githubusercontent.com/65640660/165596758-50e22ab9-c617-40cf-b197-b4067630966d.png)

y esto al crear las tablas:
![image](https://user-images.githubusercontent.com/65640660/165596855-58b90b59-c040-45ac-9956-c6beef0d3a94.png)

No se como arreglarlo, gracias de antemano

**Comment by carmebe** [comment]
Para usar SQL, te recomiendo que trabajes en Google Colab, hasta los mismos ayudantes lo recomiendan: https://github.com/IIC2413/Syllabus-2022-1/issues/106#issuecomment-1110208529
