### ISSUE TITLE
[Entrega 2] Atraso Datos .csv

### ISSUE THREAD

**Issue by Dafnemami** [IIC2413/Syllabus-2022-1#124]
Hola!,

En un [anuncio](https://cursos.canvas.uc.cl/courses/39216/discussion_topics/431106) dijeron que iban a subir los datos .csv el lunes 25, pero creo que aún no los suben porque no los encuentro. Es así o están en algún lado?

Saludos!!

**Comment by arpincheira** [comment]
Hola, debido a diversos problemas con los datos estos no han podido ser subidos aún :( 
De todas formas hoy deberían idealmente estar listos y se mandará un anuncio correspondiente. 

Lamento mucho la demora
