### ISSUE TITLE
Duda datos Entrega 2 GRUPO PAR 

### ISSUE THREAD

**Issue by gitlobo** [IIC2413/Syllabus-2022-1#126]
Holaa! Con mi compañero nos surgió una duda relacionada a los datos del csv de FPL Y PROPUESTAS. Ya que, en la Entrega 1 se enuncia que un plan de vuelo puede o no estar asociado a una propuesta de vuelo, dependiendo de su tipo (comercial, no comercial, militar). Por lo tanto, no logramos entender porqué se nos dan todos los PROPUESTAS_VUELO_ID en vez de todos los FPL_ID.
Muchas graciasss :) <3

**Comment by arpincheira** [comment]
Hola, si revisan bien los datos entregados, hay fpls que no tienen propuesta asociada y propuestas que no poseen fpl. **hint** se dejaron los ids para que se fijen en algunos detalles o repeticiones de estos.

**Comment by gitlobo** [comment]
Graciaaaas <3
