### ISSUE TITLE
Aerolinea en archivo reservas.csv

### ISSUE THREAD

**Issue by drcid98** [IIC2413/Syllabus-2022-1#127]
En el archivo reservas.csv aparece una columna llamada "aerolinea" pero es un código igual al que aparece en el archivo vuelos.csv como "codigo_vuelo". Estos 2 representan lo mismo? en caso de que no (que sería extraño), qué representa "aerolinea"?

**Comment by arpincheira** [comment]
Hola, efectivamente has encontrado un problema no menor jajaja, si, estos representan lo mismo. Puede que durante la semana subamos una v2 de los datos corrigiendo ese error y otros que puedan ir encontrando en el camino, cualquier cosa eso no debería generar grandes problemas.
