### ISSUE TITLE
[Ayudantía 3] Consultar base de datos en archivo "title_author.php"

### ISSUE THREAD

**Issue by ferperezh** [IIC2413/Syllabus-2022-1#129]
Hola en el archivo "title_author.php" hay una consulta de una base de datos llamada ted pero no la encuentro en ningun lugar
![Captura de Pantalla 2022-05-02 a la(s) 16 54 47](https://user-images.githubusercontent.com/69528837/166326880-a85be4e0-45d3-4d66-bca4-58015ac38499.png)
Ya que al buscar un title y un auto me arroja un error en este mismo archivo y no se porque arroja este error:
![Captura de Pantalla 2022-05-02 a la(s) 17 01 14](https://user-images.githubusercontent.com/69528837/166327009-e44b0b5d-3179-4529-a809-d6a890d3f874.png)

**Comment by arpincheira** [comment]
Hola, el FROM de una consulta de sql no hace referencia al nombre de una base de datos, sino que a una tabla o esquema de una base  de datos previamente definida. En este caso la tabla ted es una tabla que fue creada a partir de los datos que puedes encontrar [aquí](https://github.com/IIC2413/Syllabus-2022-1/tree/main/Ayudantias/Ayudant%C3%ADa%203/csv)

**Comment by ferperezh** [comment]
Entiendo pero dónde esta esa tabla creada ? porque intente poner uno de lo títulos de l base de datos y un autor del mismo titulo e igual me aparece un error.

**Comment by Cartterr** [comment]
Lograste solucionar le error ferperezh? Estoy intentando probar el proyecto ejemplo en ubuntu, pero me tira el mismo error:

 "No se pudo conectar a la base de datos: PDOException: SQLSTATE[08006] [7] FATAL: la autentificaci�n password fall� para el usuario" 
 
 y no estoy seguro que cambiar para solucionarlo.

**Comment by ferperezh** [comment]
hola perdon por contestar tarde pero pudiste solucionarlo?
