### ISSUE TITLE
Operador división

### ISSUE THREAD

**Issue by drcid98** [IIC2413/Syllabus-2022-1#13]
¿Se puede ocupar el operador división, a pesar de no haberlo pasado en clases?

**Comment by DomagojVrgoc** [comment]
Te refieres a division entre valores de atributos? Tipo X(id,valor) --> \sigma_{valor / 10 >=1000}?

En este caso si.

Por otro lado, no hay un operador de division entre tablas enteras.

**Comment by matiastoro** [comment]
Si te refieres al operador "division" del libro de rammakrishnan, no no se puede. Pero si lo llegaras a necesitar, lo puedes escribir en terminos de operadores vistos en clase.
