### ISSUE TITLE
Duda cambio contraseña

### ISSUE THREAD

**Issue by diegocostares** [IIC2413/Syllabus-2022-1#131]
Hola, con mi compañero queriamos cambiar la contraseña del servidor, pero el comando que nos dieron no nos está funcionando, hay otra forma de cambiar la contraseña para iniciar el `ssh grupo74@codd.ing.puc.cl` ?

**Comment by arpincheira** [comment]
Hola que comando están utilizando?

**Comment by diegocostares** [comment]
Ahi lo logre con `passwd` XD Sorry
