### ISSUE TITLE
Consulta headers aerodromo.csv de datos de entrega 2 GRUPO PAR

### ISSUE THREAD

**Issue by emolaba** [IIC2413/Syllabus-2022-1#133]
Hola! Qué significa que haya codigo_puerto_embarque_x y codigo_puerto_embarque_y (lo mismo para el codigo de pista)? Cómo interpretamos esos datos, porque a veces coinciden, otras veces son distintos, y hay distintas combinaciones para un mismo aerodromo. Muchas gracias de antemano.
Saludos

**Comment by arpincheira** [comment]
Hola, eso fue un error al momento de crear los archivos con los datos, básicamente lo que sucedió es que se repitieron los datos de dos columnas pero con un orden diferente, de ahí se genera que algunas veces coincidan y otras veces no, lo que pueden hacer en ese caso es usar por defecto los valores con X. De todas formas vamos a mandar un archivo nuevo con las respectivas correcciones y se avisará esto en el readme respectivo de la entrega 2.
