### ISSUE TITLE
Significado de licencia_actual_id en tabla de trabajadores GRUPO IMPAR

### ISSUE THREAD

**Issue by Danielggonzalez177** [IIC2413/Syllabus-2022-1#134]
No logro entender bien el dato de licencia_actual_id y como se relaciona con los otros atributos de los trabajadores y cual podría ser una interpretación ya que no depende ni del id del trabajador, la compañía aérea o el id del vuelo.  ¿Tiene alguna interpretación que pueda darle mas sentido para analizarlo?

**Comment by arpincheira** [comment]
Hola, existen algunos trabajadores que requieren de una cierta licencia para poder operar. Te recomiendo que al ver los datos veas que tipos de trabajadores existen y si hay alguna coincidencia de estos con las licencias.
