### ISSUE TITLE
Control 1 - Pregunta 3

### ISSUE THREAD

**Issue by marcosfernandezr** [IIC2413/Syllabus-2022-1#14]
En la pregunta 3 se nos pide encontrar a los capitanes que no aparecen en la tabla de **Personal**. Ahora mi duda es: **¿Es posible que una persona sea capitán de dos o más buques? o solo puede ser de un solo buque?**

**Comment by DomagojVrgoc** [comment]
Si, puede ser un capitan de dos o mas buques. Esto no deberia afectar a tu consulta.
