### ISSUE TITLE
Duda Entrega 2 - Grupo par

### ISSUE THREAD

**Issue by Manrrolo** [IIC2413/Syllabus-2022-1#140]
Hola! Tengo las siguientes consultas con respecto al diagrama de Entidad / Relación:

1. En la entrega 1 se nos pidió una tabla de Piloto y Copiloto, pero al aplicar esto con la base de datos actual ambas tablas tendrían datos en común por lo que se genera una redundancia. Entonces podemos unir ambos en una misma tabla donde contenga tanto el id_piloto y id_copiloto como atributos. 
2.  En la entrega 1 se nos pidió una tabla una tabla distinta por cada operación, pero ahora según la base de datos tienen los mismos datos a excepción de la fecha que se separa en arribo y despegue, pero al estar relacionado con FPL las operaciones ya tienen acceso a las distintas fechas, entonces si juntamos las tablas arribo y despegue en operaciones para no repetir datos entre ellos, esta ya contaría con todos los datos necesarios. No sabemos si las fechas de FPL y operaciones serán siempre las mismas
3. Tenemos un problema con Propuesta de vuelo  y FPL ya que, la mayoría de los atributos de la primera tabla están contenidos en la segunda tabla, por esto las tablas de Propuesta de vuelo y FPL generarían redundancia.

Gracias de antemano

**Comment by arpincheira** [comment]
Hola, puede ser que las siguientes respuestas sean un poco directas pero espero que sirvan para que analices bien los puntos que mencionas:

1. Se dijo que existía una tabla Piloto y Copiloto o lo asumieron? De ser lo primero... tiene sentido que un piloto dependa de un copiloto o viceversa? Si es que esto pasara... no sería raro tener en la base de datos un registro de todas las posibles combinaciones de piloto copiloto? Que pasaría si añado un nuevo dato?
2. Interesante que los distintos tipos de **operaciones** tengan datos similares.... podría implicar algún tipo de relación especial entre los **tipos** de **operaciones**? 
3. Nuevamente, existe redundancia? puede ser que exista alguna forma para que se respete la información y no se genere lo que mencionas.... ahora la pregunta es... que sería esto?

Por último te dejo un meme:
<p align="center">
  <img src="https://user-images.githubusercontent.com/37157550/167225798-1cb6d8e7-7f87-4bea-a4b2-59a8d36e58c2.png" />
</p>
