### ISSUE TITLE
Formato de datos grupo par 

### ISSUE THREAD

**Issue by fsazo** [IIC2413/Syllabus-2022-1#142]
Hola! Teníamos una duda con respecto a los datatypes en la base de datos. Al subir las tablas al servidor no sabemos como definir el datatype de latitud y longitud. En estos atributos cuando el valor es muy chico hacerlo como int genera un error y cuando el valor es muy grande hacerlo como float también genera error. Se nos ocurrió que podríamos cambiar los puntos por comas pero eso no funcionó. Entonces ahora pensamos que podemos cambiarlo a varchar pero no sabemos si está permitido.

Gracias de antemano.

**Comment by arpincheira** [comment]
Hola, no les recomiendo trabajar con varchar por nada del mundo. Te recomiendo ver la [documentación de postgresql](https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-FLOAT). Tal vez entre los tipos numéricos de representación puedas encontrar algo.
