### ISSUE TITLE
[Entrega 2] Diagrama E/R

### ISSUE THREAD

**Issue by agucova** [IIC2413/Syllabus-2022-1#144]
Hola,

Queríamos saber si el diagrama de entidad relación debe seguir el clásico modelo de diagrama E/R:

![image](https://user-images.githubusercontent.com/4694408/167275802-d8f91ea1-66bb-4785-b02a-1d68e3839ece.png)

O si puede seguir un modelo más flexible de diagrama de tablas como este:

![image](https://user-images.githubusercontent.com/4694408/167275826-6732e622-cf50-4139-9ee7-bbda70e14e6c.png)

**Comment by arpincheira** [comment]
Hola, ideal no usarlo, dado que no fue el modelo enseñado en clases, en el caso de que quieras usarlo **debes** explicar claramente cuales son los significados de la crow foot notation que estás ocupando y debes explicitar las tablas correspondientes a relaciones.
