### ISSUE TITLE
Relacion puntos - ciudades

### ISSUE THREAD

**Issue by jsilvalavin** [IIC2413/Syllabus-2022-1#147]
Hola!, tenía una duda con respecto a las relaciones entre los puntos (relacionados con las rutas) y las ciudades asociadas a los aeródromos. ¿Asumo que las ciudades siempre tienen un punto (es decir, una coordenada con nombre) que pertenece a los puntos?
Dicho de otra forma: ¿son las coordenadas de las ciudades un subconjunto de las coordenadas de los puntos que se usan para las rutas?
gracias

**Comment by arpincheira** [comment]
Hola, en lo que respecta a los datos entregados, no existe relación entre los puntos y las ciudades. Estos son más bien puntos válidos por donde puede pasar un vuelo durante su trayecto.

**Comment by jsilvalavin** [comment]
ok, gracias
