### ISSUE TITLE
[Entrega 2] Multiplicidad de trabajadores por vuelo

### ISSUE THREAD

**Issue by Dafnemami** [IIC2413/Syllabus-2022-1#149]
Hola!,

Tenemos dos dudas:

1. Según el enunciado de la E1 el contexto es el siguiente: "[...] el vuelo debe registrar que piloto, copiloto y tripulación de cabina lleva". En virtud de lo anterior nos preguntamos si debemos modelar el E/R tal que todos los vuelos tengan asociado:

- "exactamente un" Piloto 
- "exactamente un" Copiloto
- "al menos una" Tripulación de Cabina 
- "al menos un" Paramédico

Asumiendo que estos son los únicos roles que tienen los trabajadores de las compañías y que si se agregase alguno en el futuro, sería responsabilidad de ellos hacerse cargo de la modificación del E/R.

🏎

**Comment by arpincheira** [comment]
Hola, existen varias formas de modelar dicha información y te aviso al tiro que por lo menos existe una forma para hacer que añadir nuevos roles no sea un problema muy grande. En lo que respecta a las cardinalidades que mencionas arriba, dado el enunciado de la entrega 1 se pueden confirmar los primeros 2 pero los otros no necesariamente deben ser tan así.

**Comment by Dafnemami** [comment]
Comprendo, gracias. Cuando dices que para las entidades "Tripulación de Cabina" & "Paramédico" no necesariamente es así, entonces es viable pensar que se permiten vuelos que no tengan a una Tripulación de Cabina" y "Paramédico"? 

Supongo que esto también se puede poner en supuestos, me podrías confirmar? 

🏎

**Comment by arpincheira** [comment]
Podrían añadirlo como supuestos, aunque yo diría que por lo menos debe haber uno entre "Tripulación de Cabina" & "Paramédico".
