### ISSUE TITLE
Algebra Relacional

### ISSUE THREAD

**Issue by pablo-soto** [IIC2413/Syllabus-2022-1#15]
Tengo una duda, si tengo una instancia R1 con los atributos id, nombre y le quisiera hacer un join, de tal forma:
R1 join(condición : id = id) R1 resultaria en una tabla con dos atributos distintos, ambos llamado "nombre".

¿Hay alguna forma de evitar esto o renombrarlo para evitar errores al usar esa nueva tabla?

**Comment by DomagojVrgoc** [comment]
Lo tipico seria renombrar la tabla R1 de dos maneras.

Por ejemplo:
\rho(R1,X)
\rho(R1,Y)
X join_{X.id=Y.id} Y
(Igual sirve R1 join{R1.id = X.id} X; sin renombrar el Y)

Aqui \rho define dos aliases para R1 que puedes ocupar en el join ahora.

Ojo que un join no modifica la tabla original.
