### ISSUE TITLE
[Entrega 2] [Grupo Par] Duda de Certificados 

### ISSUE THREAD

**Issue by gitlobo** [IIC2413/Syllabus-2022-1#150]
Hola! Qué se hace cuando una aeronave tiene dos certificados vigentes en una misma fecha? Es decir "4459,2022-02-20,2024-02-20,Boeing KC-135,Stratotanker,44.663,PMJDMNY,," y "2387,2021-02-19,2023-02-19,Boeing KC-135,Stratotanker,44.663,PMJDMNY,," son dos certificados distintos, asociados a la misma aeronave pero que son "válidos" dentro de un periodo en común. 
Teniendo en cuenta lo anterior, cuál se debería asignar como "activo"?

**Comment by arpincheira** [comment]
Ambos estarían activos en dicha fecha.

**Comment by ebenstom** [comment]
Hola, tengo una duda con lo mismo. Cómo sabemos cuál de todos los certificados usar en una determinada consulta?
