### ISSUE TITLE
Diagrama y esquema relacional

### ISSUE THREAD

**Issue by antoniablanco** [IIC2413/Syllabus-2022-1#152]
Hola, una duda tanto el esquema como el diagrdama tienen que ser con la información de la entrega 1 de la parte par e impar. O que se refieren que este respaldada con el DGAC y aerolineas?
Muchas gracias

**Comment by antoniablanco** [comment]
Estaba revisando los datos y para cada grupo solo se encuentra parte del total. Lo cual significa que en los diagramas debemos tener todos los datos tanto DGAC y aerolineas, pero al crear las tablas solo las de del grupo par /impar?

**Comment by arpincheira** [comment]
Hola, lamento mucho la demora en la respuesta (como estaba comentado supuse que alguien más la había contestado). La idea es que utilicen los datos correspondientes a su grupo, si tienen grupo par usen los pares y si tienen grupo impar los impares.

Ahora, en lo que respecta a la relación entre los datos de la entrega 1 con aquellos de la entrega2, debes considerar que los primeros corresponden a la descripción inicial del problema por parte de un cliente, en este se describe a grandes rasgos lo que quiere tener y el funcionamiento de dichos datos, por lo que ustedes debían simplemente identificar esos datos y modelar un esquema preliminar que no necesariamente es del todo correcto. Ahora, en la entrega 2 el cliente encuentra los famosos datos y se los entrega, el problema es que estos datos no están guardados de la mejor forma posible, pero ustedes ya saben a partir de la e1 lo que significan la mayoría de los datos, así que deben analizarlos y procesarlos de forma que puedan construir una base de datos normalizada a partir de ellos y poblarla.

Ahora, respondiendo nuevamente tu pregunta, la idea es que hagan el proceso del párrafo anterior con los datos correspondientes a tu grupo(ver párrafo 1) y que luego, en la entrega 3, sean capaces de unir estos con otro grupo que tendrá los demás datos del problema.

Espero que haya. quedado claro.
