### ISSUE TITLE
Entrega 2 Estado de vuelo

### ISSUE THREAD

**Issue by Martinrsts** [IIC2413/Syllabus-2022-1#153]
Hola, en la base de datos nos entregan fpl que tienen estados pero no tienen una propuesta de vuelo asignada. Pero en el enunciado de la entrega 1 nos dicen que el estado es el del vuelo y no el del fpl. ¿Cómo un fpl puede tener un estado (distinto al de realizado o no realizado) si no tiene un plan de vuelo? Lo mismo ocurre con el código, que se supone que lo tienen los planes de vuelos pero también están en los fpl sin plan de vuelo asignado.

**Comment by arpincheira** [comment]
Hola, en el enunciado de la entrega 1 se dice que solo los vuelos comerciales poseen una propuesta de vuelo asignada, esto quiere decir que existen vuelos que no son de este tipo que no poseen una propuesta de vuelo asignada pero aún así poseen un fpl y este puede o puede no estar realizado. Además es importante notar que los fpl comparten datos con las propuestas de vuelo, es decir poseen 2 estados, uno que puede tener 3 valores y otro que solo indica si se realizó o no.
