### ISSUE TITLE
[Entrega 2] [Impar] Datos reservasV2 Pasajero Vacio

### ISSUE THREAD

**Issue by pablo-soto** [IIC2413/Syllabus-2022-1#154]
En el csv de reservas hay lineas como 
736,XLE3285-0736,4956,125,D64763364,James Johnson,Chilena,09-06-1994,11,Economica,FALSO,,,, 
Donde al final faltan los datos del pasajero de la reserva.
¿Debemos asumir que la persona que compro también es pasajera?

**Comment by arpincheira** [comment]
Hola, el dato que mencionas corresponde a un error del csv, esto se puede evidenciar especialmente porque en ese caso el que compra los pasajes ya posee un pasaje a su nombre. Gracias a tu comentario pude notar que esto sucede en las siguientes 3 ocaciones: 



  | reserva_id | codigo_reserva | numero_ticket | vuelo_id | pasaporte_comprador | nombre_comprador | nacionalidad_comprador | fecha_nacimiento_comprador | numero_asiento | clase | comida_y_maleta | pasaporte_pasajero | nombre_pasajero | nacionalidad_pasajero | fecha_nacimiento_pasajero
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
4922 | LRC9669-4922 | 1675 | 130 | J46009647 | Erica Ochoa | Italiana | 11-03-1994 | 22 | Economica | VERDADERO | NaN | NaN | NaN | NaN
2633 | COG3144-2633 | 5203 | 98 | I19062847 | Christopher Garcia | Chilena | 06-12-1986 | 9 | Economica | FALSO | NaN | NaN | NaN | NaN
736 | XLE3285-0736 | 4956 | 125 | D64763364 | James Johnson | Chilena | 09-06-1994 | 11 | Economica | FALSO | NaN | NaN | NaN | NaN

En este caso, lo ideal sería eliminar dichas filas pues pueden causar errores. Gracias por el aviso
