### ISSUE TITLE
[Entrega 2] Datos tablas

### ISSUE THREAD

**Issue by dani-sschlack** [IIC2413/Syllabus-2022-1#155]
Holaaa, me quedaba la duda de si en los archivos csv en una tabla ya se encuentra toda la info relacionada a este, por ej: si en la tabla aerodromos.csv ya se encuentran todos los aeródromos y que en la tabla  operaciones.csv se deberían ver parte de los mismos datos (de aerodromos.csv) y no pasa que hay datos de aeródromos que no están en aerodromos.csv.
No sé si me explico xd, quiero saber si es que es necesario hacer como una union de los datos entre  las tablas de los csv para crear las nuestras.
De antemano muchas gracias 👍🏼

**Comment by arpincheira** [comment]
Todos los datos que poseen un archivo correspondiente con su nombre se encuentran en su totalidad en dicho archivo. Es decir, si hay un archivo aerodromos.csv este si o si va a tener todos los aerodromos existentes.
