### ISSUE TITLE
E/R

### ISSUE THREAD

**Issue by antoniablanco** [IIC2413/Syllabus-2022-1#156]
Si es que tengo 2 entidades que dependen de la misma tercera entidad. Se puede escribir como un triangulo en el diagrama?
Muchas gracias

**Comment by arpincheira** [comment]
Te refieres a una relación de herencia? De ser así la notación es 
![image](https://user-images.githubusercontent.com/37157550/167763082-2b7dc2fd-4a2d-4257-96a0-67a4c23f5718.png)
