### ISSUE TITLE
Duda idVuelo grupo impar

### ISSUE THREAD

**Issue by camibennett** [IIC2413/Syllabus-2022-1#157]
Hola!
Estamos revisando los datos de la entrega 2 y nos dimos cuenta que los idVuelo se repiten para aerolíneas distintas. Podemos crear otro id de vuelo que sea único? o es mejor dejar la llave como (idVuelo, Aerolinea)?

Muchas gracias :)

**Comment by arpincheira** [comment]
Hola, tengo la sensación de que están cayendo en el error descrito en la issue #141, les recomiendo revisar bien esa "relación" que encontraron.
