### ISSUE TITLE
[Duda de contenido] M. E/R -> M. Relacional

### ISSUE THREAD

**Issue by Dafnemami** [IIC2413/Syllabus-2022-1#159]
Hola!,

1. Por qué no podría añadir a whisky si ocupo la opción 1? No podría simplemente agregar una nueva rama de subclase al modelo E/R y añadir una tabla "Whisky(nombre: str, origen: str, ... otros atributos)" y ya? Adjunto screenshot de la diapo de la cual surge mi duda:

![mmm](https://user-images.githubusercontent.com/53848830/167745405-0cec9a4f-24b0-41b5-9c8f-4939b97c9e5a.PNG)

EDIT: 
2. Si yo ocupo la opción 2, entonces al agregar whisky ocurre que:

- opción a: En el M.E/R se añade la subclase "Whisky"; En el M.Relacional se añade la tupla de "Whisky" en tabla "Bebida" & "Whisky"
- opción b:  No se añade nada al M.E/R; En el M.Relacional se añade la tupla de "Whisky" solo en tabla "Bebida"

3. **Si en el punto anterior la opción es B**, cómo identifico en "Bebida" si la tupla que estoy viendo es whisky u otro cosa?, entendiendo que solo puedo reconocer a las bebidas cuyo tipo es "Cerveza" o "Vino" mediante operación Join, pues **en "Bebida" no se guarda el atributo tipo.**

🏎

**Comment by carmebe** [comment]
Hola, por lo que tengo entendido, el whisky es solo un ejemplo en caso de que exista cobertura entre las entidades. Digamos que tienes más de 10 bebidas diferentes. ¿La opción que dices aún serviría?

**Comment by Dafnemami** [comment]
@carmebe Según yo es para los casos en que no hay cobertura, de haber no hay posibilidad de que aparezca otra potencial subclase. 

Con respecto a lo segundo, entendiendo que hablamos de la opción 1, es justamente eso lo que no sé: por qué no podría añadir otra tabla? quizá mi error está en pensar en que se pueden añadir cosas, i.e. pensar que tanto el M.E/R como el Esquema Relacional tienen comportamiento dinámico (modificable).

🏎

**Comment by carmebe** [comment]
@Dafnemami a lo que me refería del ejemplo del whisky, es que si en ese esquema se asume cobertura, entonces el whisky no tiene lugar en ninguna parte a no ser que sea la opción 2.
Como dije, si tienes muchas bebidas, no es recomendable (y hasta puede ser engorroso) crear múltiples tablas para cada subclase; usando la opción 2 podrías solamente crear tablas de subclase con las entidades que más te importen, y la tabla de la superclase para todo lo demás.
