### ISSUE TITLE
Formato Control 1

### ISSUE THREAD

**Issue by mpalaciosc** [IIC2413/Syllabus-2022-1#16]
¿La parte de algebra relacional la podemos hacer en latex? o de otra forma, da lo mismo el formato mientras la entrega sea en pdf?

**Comment by DomagojVrgoc** [comment]
Cualquier formato que se puede hacer en un pdf y leer. Esto incluye latex, word, o escanear una cosa escrita en papel.

**Comment by Dafnemami** [comment]
La duda del compañere arriba me dejó con una duda ¿El texto que yo escriba, que acompaña a mi desarrollo, puede ser también escrita a mano? Tenía pensando en entregar un pdf de una app para tomar apuntes en ipad. Por lo cual, toda mi tarea sería a mano.
