### ISSUE TITLE
[Entrega 2- Impar] Duda valor del vuelo

### ISSUE THREAD

**Issue by nico-sv** [IIC2413/Syllabus-2022-1#161]
Hola! en la entrega 1 nos hicieron modelar el costo de un ticket como función del peso de la aeronave y del largo de la ruta, pero en los datos que nos entregaron nos dan el valor explícito de cada vuelo. Debemos seguir modelándolo como la entrega 1 o podemos usar directamente el valor que nos entregan? y ese valor en vez de ser atributo del ticket podemos ponerlo como atributo del vuelo?

**Comment by arpincheira** [comment]
Hola, recomiendo revisar lo de los costos, puede ser que encuentres una sorpresa O.o. Con respecto a lo segundo, no puedo responder eso pues depende de tu modelo(y puede ser que tenga relación con lo primero que dije)
