### ISSUE TITLE
[Entrega 2][Par] FPL y operaciones

### ISSUE THREAD

**Issue by aurmeneta** [IIC2413/Syllabus-2022-1#162]
Hola!

¿Podemos asumir que las fechas de arribo y salida, las aeronaves y los aérodromos de salida y llegada en los datos de operaciones son los mismos que en el respectivo FPL?

Gracias!

**Comment by arpincheira** [comment]
Hola, no pueden corroborar dicha información pues estos datos pueden variar a lo largo del transcurso del vuelo.
