### ISSUE TITLE
[Entrega 2] Uso de herencia IsA en diagrama E/R

### ISSUE THREAD

**Issue by MagnaThyrsus** [IIC2413/Syllabus-2022-1#163]
Estábamos debatiendo si usar la relación IsA para dos entidades que son muy similares, pero no sabemos si se usa un solo "triángulo" para ello, como muestran algunos diagramas en internet, o uno por cada sub entidad como muestran las clases de diseño de BD. Por otro lado no estamos seguros de si el triángulo debiese estar apuntando hacia arriba, donde esta la super entidad, o hacia abajo para que la super entidad se una al lado del triángulo y no su vértice, o si eso da lo mismo.

**Comment by arpincheira** [comment]
Hola, cualquiera de las notaciones va a ser considerada como válida, creo que en la issue #156 muestro un ejemplo de dicha relación utilizando la notación de 1 triángulo
