### ISSUE TITLE
cardinalidad en el archivo ruta

### ISSUE THREAD

**Issue by antoniablanco** [IIC2413/Syllabus-2022-1#166]
Hola para el grupo pares se entrego el archivo Ruta donde viene incluido cardinalidad, estuve revisando la entrega 1 y no encontre este atributo. Entonces quería preguntar a que se refiere, es parte de la ruta, del punto o de otro?
Muchas gracias

**Comment by carmebe** [comment]
Hola, esta pregunta ya fue respondida: https://github.com/IIC2413/Syllabus-2022-1/issues/143
