### ISSUE TITLE
[Entrega 2] Duda dependencias en modelo relacional

### ISSUE THREAD

**Issue by J0SEF4** [IIC2413/Syllabus-2022-1#172]
Buenas. Mi duda, es con respecto a como se cuales son mis dependencias respecto a mi modelo relacional? Como las describo para verificar 3NF? Me podrían dar un ejemplo?

Saludos.

**Comment by arpincheira** [comment]
Ustedes deben principalmente hacer 2 cosas, lo primero es listar las dependencias de las tablas y lo segundo es justificar el motivo por el cual puedes decir que se encuentra normalizada dicha Tabla en base a sus dependencias. Lo que se espera que **no hagan** es que luego de listar todas las dependencias hagan una justificación genérica o pongan la definición de BCNF-3NF y digan que se cumple, esto probablemente **no tendrá puntaje** pues, para poder ver la definición, basta que veamos las diapositivas del curso o busquemos por internet.

A continuación te muestro un ejemplo de lo que hay que hacer:

## Normalización

Si les damos una tabla que sea `direcciones` y tenga lo siguiente:

id  | nombre_direccion | numero_direccion   | comuna         | país
---|-------------------|--------------------|-------------|-------|
1   | x    | n_x | hola| Chile
2  | y    | n_y | hola| Chile
3  | z    | n_z | chao| Chile
4  | w   | n_w | ciao| Italia

Lo que esperamos que hagan es crear tablas del estilo
`direcciones`
id        | nombre_direccion  | numero_direccion    | Comuna_id
---------------- |--------- |----------|----------|
1       | x    | n_x | 1
2       | y   | n_y | 1
3      | z    | n_z | 2
4       | w  | n_w | 3


`comunas`


id        | nombre    | pais_id
---------------- |--------- |----------|
1       |  hola   | 1
2       | chao   | 1
3      | ciao   | 2


`paises`


id        | nombre    |
---------------- |--------- |
1       |  Chile
2       | Italia

## Justificación de las dependencias

Del ejemplo de recién podemos ver las siguientes dependencias:
Pais: id -> nombre
communa: id -> nombre
dirección: id -> nombre_dirección, número_dirección

Ahora, podemos justificar esto de la siguiente forma:
País: Podemos observar que el id del país corresponde a una superllave* la cuál fue construía por nosotros al momento de realizar la normalización de los datos, esta es única y a partir de ella se puede determinar el nombre del país y los diversos atributos que lo componen e identificar la entidad en el esquema.

Comuna: Similar al caso anterior, podemos identificar que el id construído también corresponde a una llave construida por nosotros y por definición es única, permitiendo identificar la entidad al interior del esquema.

Dirección: A dufereicua de kis cassis anteriores, id corresponde a una superllave que fue otorgadaen los datos originales, esta permite determinar tanto el nombre de dirección como número de dirección los cuales dependen en su totalidad de dicha información(notar que el nombre se puede repetir y el número también por lo que el par número, nombre y posibles otros atributos dependen del la dirección como tal y no de otras entidades.

superllave*: se define como superllave como un ser de atributos de una relación tales que todas las relaciones están asignadas a dicha variable en el esquema relacional.

**Comment by J0SEF4** [comment]
Y perfecto ahora entendí perfecto. Solo me queda la duda, de que esto seria 3NF o BCNF y por que?
