### ISSUE TITLE
Duda operaciones grupo par

### ISSUE THREAD

**Issue by fsazo** [IIC2413/Syllabus-2022-1#173]
Hola!
Tenía una duda respecto a las operaciones. En la tabla está el código de pista de arribo y el código de puerto de arribo además del código de pista de despegue y el código de puerto de despegue, estos atributos se encuentran en común entre las operaciones arribo y despegue? O son independiente para cada operación?

Y tenía otra duda sobre el modelo relacional. Este se debe hacer con tablas para mostrarlo en el pdf de la entrega o se hace con código en el servidor (como se vio en la clases)?

Gracias

**Comment by arpincheira** [comment]
1._ Si miramos la entrega 1 podemos ver lo siguiente
<img width="968" alt="Captura de Pantalla 2022-05-12 a la(s) 22 14 45" src="https://user-images.githubusercontent.com/37157550/168197962-46fcd9bf-78cb-4027-b67a-24953d3c1103.png">
Eso quiere decir que existen algunos datos que están relacionados a otros y no, no dependen como tal de la operación. (no me puedo explayar mucho porque estaría dando alguna respuesta de la entrega en si misma).

2. Ustedes deben entregar un **esquema** y un **diagrama e/r**. El primero de esto lo puedes ver explicado con mayor detalle en la issue #26, notar que la idea es que para esta entrega el esquema que entreguen sea uno ya normalizado y que incluya declaración de llaves primarias y foráneas, además de los tipos de los datos. El segundo de estos lo vieron en clases y debe estar basado en el primero, ver issue #165

**Comment by tamyhan** [comment]
Hola! Tengo una duda con respecto a esto.
Según lo que dice en esa parte del enunciado, se generan dos operaciones distintas: una de arribo y una de despegue. Pero en el csv los datos de arribo y despegue corresponden a un mismo operacion_id, así que no entiendo cómo definir cuáles operaciones son de arribo y cuáles de despegue.

**Comment by AntonioDoberti** [comment]
Tengo la misma duda que @tamyhan

**Comment by arpincheira** [comment]
Cualquiera de las dos es válida, ojo que puede suceder que este id esté por algo(**hint?**)
