### ISSUE TITLE
Entrega 2 / Accent sensitive or insensitve?

### ISSUE THREAD

**Issue by larryuc** [IIC2413/Syllabus-2022-1#174]
Estimados, en las instrucciones se habla que los datos en la consulta seran case-insensitive y con
matching parcial.

Mi duda es y para los acentos? Sera Accent sensitive o accent insensitve?
Gracias.

**Comment by arpincheira** [comment]
Accent insensitive, aunque no nos enfocaremos mucho en realizar pruebas de esto último.

**Comment by larryuc** [comment]
Matching parcial para búsquedas con letra ‘A’ basta con que sea “comenzando con A” o “contiene A”

vale decir, el criterio es… A%, o %A%? también?
