### ISSUE TITLE
[Entrega 2] Dependencia de latitud y longitud con país

### ISSUE THREAD

**Issue by negamartin** [IIC2413/Syllabus-2022-1#177]
Hola!

De cierta manera es posible determinar el país a partir de la latitud y longitud, pero es un proceso complicado, para ciertos puntos no hay respuesta y en otros la respuesta es incluso polémica.

Mi pregunta es, ¿es necesario incluir esta dependencia?

**Comment by arpincheira** [comment]
Hola, la respuesta de la issue #147 también aplica a esto.

**Comment by negamartin** [comment]
Perfecto, gracias.
