### ISSUE TITLE
[Entrega 2] Separación entre piloto y copiloto

### ISSUE THREAD

**Issue by negamartin** [IIC2413/Syllabus-2022-1#178]
Hola!

En el enunciado de la entrega 1 se divide a los trabajadores en piloto y tripulación de cabina. Sin embargo, en los datos existen pilotos, copilotos y varios roles más.

Es necesario mantener esta información? O se puede agrupar pilotos y copilotos simplemente como "pilotos" y el resto como "tripulacion de cabina"?

Muchas gracias!

**Comment by arpincheira** [comment]
Hola, el rol que posee un trabajador al interior del vuelo es importante. Ahora, pueden existir distintos tipos de trabajadores(**hint?**) y estos se puedan agrupar como quieran, pero es importante que la distinción del rol que toman en los vuelos que participan no se pierda.
