### ISSUE TITLE
Duda 3NF

### ISSUE THREAD

**Issue by CataLebe** [IIC2413/Syllabus-2022-1#179]
Para dejar todas nuestras relaciones en 3NF debemos simplemente considerar lo que nos da el enunciado de la primera entrega o creamos relaciones nosotros del tipo: tipo de vuelo define el nro de pasajeros ?
Me pasa que si solo tomo lo que el enunciado presenta explícitamente muchas variables, casi todas, suelen depender tan solo de id o algún código cosa que no se si está bien. Me cuesta encontrar dependencias además de la de id.

Desde ya muchas gracias

**Comment by arpincheira** [comment]
Hola, recomiendo ver la issue #172 en donde se habla un poco del tema de las dependencias y cómo debería hacerse la demostración solicitada. Es importante destacar que ese es un caso simplificado pero la base de la justificación está dentro de lo esperado y, en el caso de querer justificar 3nf, debes hacer un par de pasos menos pues solo se pediría que cumpla con 2nf y que no hayan dependencias transitivas.

Ahora, con lo que dices, puede darse que muchas de estas dependan de un id y eso no sería erróneo, sobretodo en los casos en los que puedes identificar que estos son llaves únicas y que permiten referencias de forma correcta a una entidad, lo importante es que sepas identificar realmente la dependencia. Por ejemplo, en el caso de la issue a la que hice referencia más arriba, puede pasar que alguien considere en la tabla original que el país depende de la dirección, algo que claramente sería incorrecto porque no es una dirección la que define el país en la que se encuentra sino que el país debería ser una entidad independiente, además de que eso mismo se podría dar a la inversa pues pueden existir dos direcciones iguales en países distintos.
