### ISSUE TITLE
Duda sobre Producto cruz

### ISSUE THREAD

**Issue by drcid98** [IIC2413/Syllabus-2022-1#18]
Sea una relación R1 con atributos "a" y "b" y una relación R2 tal que esta sea una copia exacta de R1. Si realizo R1 x R2 ¿como quedarían los nombres de los atributos de la relación resultante?

de esta manera -> a | b | a | b

o se esta manera -> R1.a | R1.b | R2.a | R2.b

En caso de que sea la primera, ¿como podría hacer referencia al primer (de más a la izquierda) par de atributos?

**Comment by drcid98** [comment]
Sii, me queda claro que para acceder a atributos con mismo nombre de relaciones distintas debo hacerlo asi, pero es así mismo en el caso que mencioné? en donde en una misma relación (resultante de R1 x R2) hay 2 atributos con el mismo nombre.

**Comment by TamaraCucumides** [comment]
Sip, funciona de la misma manera. De hecho, no está soportado que en una misma tabla hayan atributos con el mismo nombre.

**Comment by drcid98** [comment]
Muchas graciaaas!
