### ISSUE TITLE
Pregunta random dependencias 

### ISSUE THREAD

**Issue by dani-sschlack** [IIC2413/Syllabus-2022-1#180]
hola xd, es que me queda la duda de si por esas cosas de la vida tengo una tabla con un atributo eso cómo es que se entiende en cuanto a dependencias, yo creo que no tiene ninguna xd (pero no estoy segura), lo otro, si en otra tabla yo tengo tuplas con dos atributos pero estos se definen en conjunto tipo (id_conductor, id_patente_auto), porque puede darse que un conductor tenga más de dos autos ¿eso tampoco tendría dependencia cierto? (porque por un lado del conductor depende la patente pero igual puede entenderse que la patente defina a su dueño(?)) ¿o se escoge una de las posibles dependencias nomás?

**Comment by arpincheira** [comment]
Hola, la verdad es que no entiendo del todo tu pregunta, podrías reformularla por favor?
