### ISSUE TITLE
[Entrega 2] Nombre Aerodromo

### ISSUE THREAD

**Issue by mhrobles** [IIC2413/Syllabus-2022-1#181]
Mi pregunta es: ¿El nombre de cada aerodromo es unico? o me convendría asignarle un id?

**Comment by arpincheira** [comment]
Normalmente se recomienda la asignación de ids para evitar casos en los que dos elementos posean una característica que se puede eventualmente repetir. En este caso los nombres creo que son únicos, pero recomiendo que revisen bien que no hayan repeticiones en los datos y que creen un id :D
