### ISSUE TITLE
[Entrega 2 Impar] Duda valor vuelo

### ISSUE THREAD

**Issue by angegazitua** [IIC2413/Syllabus-2022-1#182]
¡Hola! Teníamos una duda sobre el valor/precio del vuelo. En la entrega 1 mencionaban que el valor del vuelo se calculaba a través de la ruta y el peso de la aeronave. Sin embargo, ahora en los archivos csv nos entregan el valor explícitamente. Nos preguntábamos si podemos ocupar este valor directamente o debemos seguir con cómo lo estábamos modelando anteriormente. 

Pd: Hay una issue similar, pero no entendimos la explicación :(

¡Gracias!

**Comment by arpincheira** [comment]
La explicación es que no hay una explicación explícita que se les pueda dar :,( Es por eso que en la issue #161 se les indica que revisen los datos, que en una de esas pueden encontrar la respuesta a lo que preguntan a partir del análisis de los precios y sus respectivas repeticiones(puedes ver que algunos costos se repiten siguiendo un determinado patrón). Esto les debería ayudar a contestar su duda.

**Comment by conicorreag** [comment]
Hola! Hemos probado con todas las columnas de todas las tablas y no hemos encontrado ningún patrón. Nos pasa que precios distintos tienen los mismos atributos (aeronave, peso, modelo, carnalidad de la ruta). Podrían darnos alguna indicación de a que se refieren con este patrón?

**Comment by arpincheira** [comment]
<img width="944" alt="Captura de Pantalla 2022-05-16 a la(s) 9 16 10" src="https://user-images.githubusercontent.com/37157550/168601060-b641991d-5465-4db4-a9e2-57349bcc374e.png">

Eso es todo lo que necesitan, no puedo ahondar más en el tema.
