### ISSUE TITLE
Duda trabajador 4385

### ISSUE THREAD

**Issue by simonmb12** [IIC2413/Syllabus-2022-1#183]
Hola!
Arreglando los datos nos dimos cuenta que hay solo un trabajador sin vuelo_id. Quería saber si esto está correcto o es un error que tuvo al completarse los datos (si es intencional o no).

**Comment by arpincheira** [comment]
Un trabajador sin vuelo_id? Están hablando del archivo trabajadores.csv? Están seguros de que esto pasa?

**Comment by simonmb12** [comment]
Sii, ósea hay algunas filas donde no se le pudo los datos de vuelo a algunos trabajadores..
Por ejemplo acá

![Captura de Pantalla 2022-05-15 a la(s) 09 26 26](https://user-images.githubusercontent.com/89275951/168475344-63d3c729-fb28-49e8-95eb-9660a6d6c83e.png)

**Comment by AmeliaIacobelli** [comment]
Hola! Me aparece lo mismo con la trabajadora de id 3. No tiene ni vuelo, ni rol, ni compañía.

**Comment by arpincheira** [comment]
ChanChanChan... han encontrado a la gran Linda Paul, la cuál en efecto, no trabaja en vuelos comerciales. Este caso puede pasar y su modelo debe considerarla y ser capaz de soportarla.(va a ser importante en la entrega 3) Además aprovecho de informar que hay otros 5 trabajadores que tampoco participan en vuelos ni forman parte de compañías(también deben ser capaces de soportarlos).
