### ISSUE TITLE
[Entrega 2 Par] Consultas SQL

### ISSUE THREAD

**Issue by carmebe** [IIC2413/Syllabus-2022-1#185]
Hola, tengo varias preguntas con respecto a esta parte:

1. ¿Qué tan explicativo y exacto debe ser el _output_ de cada consulta? Por ejemplo, si nos piden las propuestas de vuelo, al hacer referencia al aeródromo hay que proyectar su nombre o código ICAO en vez del id.
2. En la consulta 3, cuando se piden los pilotos, ¿estrictamente se piden las personas que han sido pilotos de al menos un FPL, o esto también incluye los que solamente hayan sido copilotos?
3. En la consulta 4, sabemos que el único atributo que hace referencia a los pasajeros es ``max_pasajeros`` en un FPL, pero este tiene fechas/horas y aeródromos de salida y llegada, y además puede estar vinculado a operaciones, las cuales pueden tener su propia fecha/hora. Con afluencia de pasajeros en un aeródromo y fecha/hora, ¿se refiere al de salida, al de llegada, al de despegue o al de arribo?
4. En la consulta 5, ¿se asume que un vuelo realizado de una aeronave ocurre en la **fecha de despegue**? ¿Qué sucede si la fecha de despegue está entre medio de las fechas ingresadas, pero la de arribo se pasa del intervalo, o en el caso en que el de despegue esté fuera de las fechas asignadas pero el de arribo esté dentro?
5. En la consulta 6, ¿el par piloto-copiloto es igual cuando el copiloto es piloto y viceversa? (es decir, (P,C) = (C,P)). Si es así, ¿entonces se toman como duplicados y estos no se consideran en la consulta?

**Comment by arpincheira** [comment]
1._ Recomiendo proyectar la totalidad de la entidad, mostrar solo un atributo, aunque sea único, puede generar problemas al momento de realizar la corrección, además de que en la vida real no te sirve de nada que la página web muestre solo ids(los que las usan por lo general no tienen acceso a la base de datos o buscan atributos, no solo identificadores).

2._ Pilotos y copilotos, toda persona que posea licencia de piloto. Igual tendremos esto en cuenta al mmomento de hacer la corrección.

3._ Con pasajeros nos referimos al potencial de pasajeros dados los vuelos que se dan. Se refiere tanto a la operación de salida y de llegada.(Piensa que para salir o llegar los pasajeros deben estar en el aeropuerto en algún instante del bloque horario).

4._ Considera que una aeronave realiza un vuelo cuando esta despegue y/o aterrizaje se encuentra entremedio de las fechas solicitadas, este intervalo de tiempo incluye también las fechas ingresadas.

5._ PC = CP. Sí, se toman como duplicados y no se consideran en la consulta(deben poner la pareja una vez nomás).

**Comment by carmebe** [comment]
Buena, eso si, ¿a qué te refieres con "potencial de pasajeros"? ¿No importa la cantidad de pasajeros que haya tenido el vuelo, sino la operación del vuelo como tal? (según lo que dijiste entre paréntesis)

**Comment by arpincheira** [comment]
El problema es que ustedes no cuentan con una forma de obtener la cantidad de pasajeros que tomaron dicho vuelo sin ingresar a los datos de los grupos impares.

Si, solo considera los vuelos que han sido efectuados.
