### ISSUE TITLE
Duda donde y cómo subir la entrega

### ISSUE THREAD

**Issue by simonmb12** [IIC2413/Syllabus-2022-1#188]
Hola!
Tengo una duda de cómo subir la entrega y en que carpetas. 
![Captura de Pantalla 2022-05-15 a la(s) 15 22 49](https://user-images.githubusercontent.com/89275951/168490363-1c59af15-4008-4291-acd5-c48e791214ae.png)
Para poder hacer esto debemos crear una carpeta Home, que dentro tenga una carpeta grupox y dentro de esa carpeta crear la carpeta Sites?

Y las tablas para la base de datos deben ser creadas directamente en el servidor grupoXe2?

**Comment by simonmb12** [comment]
Además, para poder poblar las tablas en el server, necesito subir los archivos csv al mismo servidor o puedo referenciarlos desde una carpeta en mi escritorio? Estaba viendo la ayudantía de hace unos semestres y no me queda muy claro como la terminal sabe a que archivo csv se refiere el ayudante al poblar la tabla.

**Comment by arpincheira** [comment]
Hoola, creo que te estás sobrecomplicando con el enunciado. Los archivos para la página web deben estar en la carpeta Sites que ya se encontraba en el servidor. Por otro lado, el informe de la entrega y los csv deben estar en la carpeta Entrega2. A continuación mando una foto de ejemplo:
<img width="533" alt="Captura de Pantalla 2022-05-15 a la(s) 18 36 19" src="https://user-images.githubusercontent.com/37157550/168496805-ac71170a-77ef-4be5-832a-11759b267976.png">
