### ISSUE TITLE
[Entrega 2] Datos csv

### ISSUE THREAD

**Issue by Piolawa** [IIC2413/Syllabus-2022-1#189]
Hola! Tengo 2 preguntas:

1.- En los csv que debo crear puedo agregar el atributo id a las relaciones que no la tengan o debo trabajar con lo que me dan nomás? por ejemplo, en rutas.csv no está el id de los puntos y en la nueva tabla que queria crear puntos.csv queria que su llave primaria fuera id_punto, y asi que calzara con el modelo Entidad-Relación que creeamos

2.- El nombre del punto es único?

**Comment by arpincheira** [comment]
1._ Mira la issue #172, igualmente la respuesta es sí, puedes crear ids únicos por tu cuenta.
2._ No necesariamente, aunque creo que en la porción de datos entregada si lo es.

**Comment by Piolawa** [comment]
Gracias!
