### ISSUE TITLE
Duda sobre proyeccion

### ISSUE THREAD

**Issue by jsilvalavin** [IIC2413/Syllabus-2022-1#19]
Hola! Mi duda es la siguiente: puedo proyectar un par de atributos de una relacion pero en orden inverso? es decir, puedo obtener R(b,a) a partir de un R(a,b) con una proyeccion?
Gracias :)

**Comment by matiastoro** [comment]
Podrías proyectando los atributos en orden inversio, pero no tiene ninguna utilidad.
