### ISSUE TITLE
[Entrega 2] Tablas y datos de grupo par e impar

### ISSUE THREAD

**Issue by larryuc** [IIC2413/Syllabus-2022-1#191]
Estimados,
Tengo una duda de enunciado, en el diagrama E/R final y sus tablas creadas en la nueva base de datos, se debe considerar los datos del otro grupo.

Por ejemplo en mi caso somos grupo Impar, y los archivos CSV del grupo par hacen referencias a certificaciones. Nuestro modelo de grupo impar igual debe considerar  ahora la existencia de esos datos posibles para el futuro (Entrega 3)?

Vale decir, debemos crear la columna certificaciones pese a que en el grupo impar entrega 1 y entrega 2 no se menciona?

**Comment by arpincheira** [comment]
Deben incluirlo como un dato adicional, como si fuera un atributo cualquiera. En el caso de los certificados pueden obviarlos al momento de justificar las dependencias en la justificación de la normalización. En resumen, sí deben crearla, pues se menciona en la entrega 1 y se entrega dicho dato en la entrega 2, pero no deben considerarlo al momento de hacer la justificación de la normalización del esquema.
