### ISSUE TITLE
[Entrega 2] Nuevas tablas

### ISSUE THREAD

**Issue by Alzvil** [IIC2413/Syllabus-2022-1#192]
Hola! Ví en una issue que se debían crear nuevos .csv normalizados, ¿Esto es estrictamente necesario si creamos tablas normalizadas pero solo con comandos sql?

**Comment by arpincheira** [comment]
No es necesario, solo recomendado. Esto se debe a que nosotros vamos a revisar lo que declaren en el informe y lo que tengan en la bdd correspondiente, no los csv(estos solo sirven como apoyo en casos especiales al momento de corregir/recorregir).

**Comment by Alzvil** [comment]
Yap gracias! Entonces se podría utilizar, por ejemplo, vistas materializadas o sería preferible buscar otros métodos?
