### ISSUE TITLE
FPL y propuestas de vuelo

### ISSUE THREAD

**Issue by CataLebe** [IIC2413/Syllabus-2022-1#193]
Algo que me causa dudas que un FPL posee los mismos datos que una propuesta de vuelo además de otros. Por lo que me haría lógica asociar el FPL al id de la propuesta de vuelo con la que está relacionado para evitar redundancia y no reescribir información. Pero no todos los FPL están asociados a una propuesta de vuelo de forma que independiente de evitar la redundancia no sabría como relacionarlos.
Desde ya muchas gracias

**Comment by arpincheira** [comment]
Hola, tal y como mencionas el FPL y la propuesta de vuelo comparten una misma estructura en lo que respecta a varios de sus atributos (pero no en todos). A modo de "pista" te recomiendo ver bien la posibilidad de que revises sobre alguna relación de entidades que permita describir algo similar a lo descrito anteriormente.
