### ISSUE TITLE
Id es necesario ?

### ISSUE THREAD

**Issue by CataLebe** [IIC2413/Syllabus-2022-1#195]
Es necesario utilizar un id en todas las tablas, o si existe otro identificador único como un código es suficiente ?

Gracias !

**Comment by arpincheira** [comment]
Hola, no es necesario usar un id. Si bien esto es altamente recomendado si tu encuentras un atributo que sea justificadamente único entonces puedes usar este como identificador.(notar que debes justificarlo igual y debes tener cuidado con los supuestos que tomes en base a los datos que se te entregan pues existen en los datos entregados algunos atributos que no se repiten pero eso no implica que estos sean realmente únicos en el problema).

**Comment by CataLebe** [comment]
Gracias !
