### ISSUE TITLE
[Entrega 2] Formato esquema relacional

### ISSUE THREAD

**Issue by Piolawa** [IIC2413/Syllabus-2022-1#196]
Hola!

Es suficiente para indicar que un atributo es llave primaria subrayarlo y que un atributo es llave foranea indicando de que relación proviene con un punto? O es necesario escribirlo explicitamente.

- 1) Ejemplo de la primera opción: 

Persona( subrayado[rut]: varchar, nombre:varchar, email:varchar)
Estudiante(subrayado[Persona.rut]:varchar)

- 2) Ejemplo de la segunda opción:

Persona( rut: varchar, nombre:varchar, email:varchar)
Llave primaria: rut

Estudiante(rut:varchar)
Llave primaria: rut
Llave foránea: rut , proveniente de Persona

Es decir:  es válido i), ii) o cualquiera de las dos está bien?

**Comment by arpincheira** [comment]
Recomiendo la segunda pues es más sencilla y evita posibles confusiones.
