### ISSUE TITLE
Llaves foráneas en tablas(?)

### ISSUE THREAD

**Issue by Gjescalante** [IIC2413/Syllabus-2022-1#198]
Saludos, escribo para preguntar: ¿es necesario que las llaves foráneas sean una tabla en la bdd? pues dejando los atributos en las respectivas clases se puede hacer un join directo, y por lo que entendimos en la  issue #172 es lo que hay que hacer. Gracias por su tiempo.

**Comment by matiastoro** [comment]
Hola, quizás preguntas si es necesario que las relaciones sean siempre una tabla. Si es esa tu pregunta, la respuesta es no. Todo depende de las multiplicidades de tu modelo E/R. En la clase 06 vimos como transformar modelo E/R a modelo relacional, y habían casos donde no era necesaria una tabla intermedia, y se dejaba la llave foranea directamente en una de las dos tablas. Esto se da en particular cuando tienes una relacion entre dos entidades donde la participación es total: es decir una entidad esta relacionada a 1 y solamente 1 otra entidad.
