### ISSUE TITLE
[Entrega 2] Duda llaves foráneas 

### ISSUE THREAD

**Issue by J0SEF4** [IIC2413/Syllabus-2022-1#199]
Hola! Tengo una una duda, con respecto a que  tengo la tabla `a` y dentro de esta tengo la llave foránea de la tabla `b` y la tabla `b` tiene una llave foránea de la tabla `c` . Ahora mi duda es que en el modelo relacional de la tabla `a` añado la llave foránea de `b`, pero ahora ¿también debería añadir la llave foránea de la tabla `c` aunque este dentro de `b` , dentro del modelo relacional de la tabla `b`?

[Editado]

**Comment by arpincheira** [comment]
Hola, es importante recalcar que no debes compartir detalles de la implementación de tu respuesta en una issue, de ahí la edición realizada.

Ahora, no entiendo del todo a que te refieres con añadir la llave foránea de una tabla dentro del modelo relacional de la otra, tampoco me hace mucho sentido que la tabla `a` deba tener la llave foránea de una tabla que no está directamente relacionada. No se si puedes explayar un poco más tu pregunta
