### ISSUE TITLE
Formato Output Entrega 2 

### ISSUE THREAD

**Issue by Martinrsts** [IIC2413/Syllabus-2022-1#200]
Hola, en el enunciado dice _Para automatizar la correcci´on y tener su nota lo antes posible, les pedimos
que respeten el formato de output que se ense˜nar´a en la ayudant´ıa del viernes, 23 de Abril._ Nosotros no pudimos ir a la ayudantía, cuál sería ese formato?

**Comment by arpincheira** [comment]
Hola, se refiere a un formato de tablas, estas permiten visualizar la información de forma  mucho más sencilla que una lista o un conjunto de párrafos y es mucho más fácil de implementar que un diseño más detallado como podrían ser tarjetas en las que se describan los atributos de las entidades a mostrar. 

Ahora, algo que es importante notar es que en la ayudantía también se muestra que las respuestas deberían incluir los atributos mismos de la entidad a mostrar y no solo los ids, esto también está pensado a fines de corrección pues lo segundo complica bastante la corrección, sobretodo para las entidades que crearon ustedes cuyos ids nosotros desconocemos.

**Comment by larryuc** [comment]
Tienen a algún ejemplo de este formato enseñado de tablas? O se refieren al típico "diagrama" de tablas relacionadas con tipos de datos, primary key y flechas de foreign key que generan los administradores de base de datos? Ejemplo: datagrip diagrams.

**Comment by arpincheira** [comment]
Hola, el formato de output solicitado no tiene mucho que ver con este "diagrama" que mencionas, más allá de que ambos son tablas. Un ejemplo de lo que menciono es el siguiente:



title | author | date | views | likes | link
-- | -- | -- | -- | -- | --
Climate action needs new frontline leadership | Ozawa Bineshi Albert | December 2021 | 404000 | 12000 | link
The dark history of the overthrow of Hawaii | Sydney Iaukea | February 2022 | 214000 | 6400 | link
How play can spark new ideas for your business | Martin Reeves | September 2021 | 412000 | 12000 | link
Why is China appointing judges to combat climate change? | James K. Thornton | October 2021 | 427000 | 12000 | link
Cement's carbon problem — and 2 ways to fix it | Mahendra Singhi | October 2021 | 2400 | 72 | link
The tragedy of air pollution — and an urgent demand for clean air | Rosamund Adoo-Kissi-Debrah | October 2021 | 422000 | 12000 | link
The myth of Narcissus and Echo | Iseult Gillespie | February 2022 | 412000 | 12000 | link
You deserve the right to repair your stuff | Gay Gordon-Byrne | August 2021 | 455000 | 13000 | link
What nature can teach us about sustainable business | Erin Meezan | February 2022 | 66000 | 1900 | link
The origins of blackface and Black stereotypes | Dwan Reece | March 2019 | 584000 | 17000 | link
A sex therapist's secret to rediscovering your spark | Ian Kerner | August 2021 | 87000 | 2600 | link


Este se pude conseguir utilizando los tags `<table>, <tr>, <th>` y `<td>` que posee html.(y por consecuencia php)
