### ISSUE TITLE
[Entrega 2] Aerodromo salida y llegada, grupo impar

### ISSUE THREAD

**Issue by J0SEF4** [IIC2413/Syllabus-2022-1#201]
Buenas tardes. 
Esperando que estén bien. Me contacto por esta vía, dado que tengo una duda de como establecer el aeródromo de salida y llegada de la tabla vuelo. Estaría bien dejarlo como una tabla aparte y tenga estos dos atributos? Y si es así no sabría bien como relacionarlo con la entidad aeródromo.
O otra opción, se que en el esquema lo pongo con el diamante, uno para llegada y otro para salida relacionando desde vuelo a aeródromo, pero eso como se ve en el modelo relacional como se escribiría? dentro de la entidad aeródromo?

Saludos y perdón estoy muy confundida en ese tema.

**Comment by arpincheira** [comment]
Hola, no podemos contestar esto en Issues pues es parte de lo que deben resolver en la entrega. Lo lamento.
