### ISSUE TITLE
Duda consulta 5 GRUPO PAR

### ISSUE THREAD

**Issue by gonzaloi21** [IIC2413/Syllabus-2022-1#202]
Hola! 
Nos queda la duda de que si los vuelos que nos piden listar son todos o solo aquellos vuelos que fueron  aceptados.

gracias

**Comment by carmebe** [comment]
Hola, me sumo a esta pregunta, dado que según los datos, hay operaciones en vuelos que no se han realizado y que además quedaron pendientes o rechazados, lo cuál me parece extraño.

**Comment by arpincheira** [comment]
Hola, creo haber contestado a esto en la issue #185. Consideren solo los realmente realizados.
