### ISSUE TITLE
[Entrega 2] Duda buena práctica: ¿generar identificadores en excel o en postgres?

### ISSUE THREAD

**Issue by fagiannoni** [IIC2413/Syllabus-2022-1#203]
¡Hola! 👋 

Nos entró la duda sobre si es mejor práctica no generar columnas de `id` a mano (con excel), sino que en vez de eso generarlas directamente con el tipo `serial` de Postgres. Con generarlas a mano me refiero crear las columnas en el archivo `.csv` y luego declararlas en Postgres como dato de tipo `integer`.

Estaré atento, desde ya ¡muchas gracias! ✨ 
Saludos

**Comment by arpincheira** [comment]
No hay una restricción en lo que respecta a la entrega entre generar los ids con serial o "a mano". La gran diferencia que puede existir es que generar los ids con serial posee un par de inconvenientes como la posibilidad de que por accidente añadamos dos veces los datos del csv y queden duplicados los datos con distintos serial o que al usar serial se pierde de cierta forma el Tracking de nuestro id, haciendo un poco más complejo crear las tablas relacionadas. 

Ahora, cuando uno trabaja en proyectos por lo general no genera los datos a mano sino que lo hace a través de un ORM el cual se encarga por detrás de generar un identificador único(no siempre, pero si generalmente) el cuál puede ser de gran utilidad para evitar generar ids numéricos que pueden comprometer de una u otra manera información sensible, algo que se produce con serial. Yo diría que utilizar `serial` en general  no es una mala práctica pero no siempre va a ser lo óptimo.

**Comment by fagiannoni** [comment]
Perfecto, me quedó clarísimo.
¡Muchas gracias! 😄
