### ISSUE TITLE
[Entrega2] (Impar) problemas con licencia_actual

### ISSUE THREAD

**Issue by joalonsosch** [IIC2413/Syllabus-2022-1#204]
Hola!

Espero que se encuentren bien.
Me surgió una duda con el atributo licencia_actual de la tabla trabajadores de los grupos impares, porque no veo una clara relación con otros atributos, lo que queda en evidencia al analizar a personas que cuentan con licencia pero no trabajaron.
Adjunto un ejemplo.

Muchas gracias desde ya!

![Captura de pantalla (641)](https://user-images.githubusercontent.com/69523214/168716980-ddb91756-4d86-47ad-8dc3-b4e408770865.png)

**Comment by arpincheira** [comment]
Hola, si revisas el enunciado de la entrega 1 podrás ver que hay un cierto tipo de trabajadores que poseen licencia. Saludos

**Comment by pablo-soto** [comment]
Quisiera aprovechar la issue para consultar, qué pasa con los trabajadores que tienen dos licencia_actual_id? es un error de los datos, o un trabajador puede tener multiples licencias?

**Comment by arpincheira** [comment]
Lo segundo.
