### ISSUE TITLE
[Entrega 2] correctitud de datos

### ISSUE THREAD

**Issue by larryuc** [IIC2413/Syllabus-2022-1#205]
Estimados,
En la carga de datos se habla de preprocesamiento, pero por ejemplo si hay datos que no son coherentes, ejemplo ciudades que no existen en ese país o aeropuertos inconsistentes con la ciudad. ¿Estos deben ser corregidos?

Generalmente el preprocesamiento de datos se limita a los nulos, truncamientos y errores de tipeo o lecturas computacionales incorrectas con distinta codificación o "collation". 

Esta segunda operación va más asociada a la calidad de los datos, evidentemente con una corrección manual se podrían corregir, pero esto alteraría la naturaleza original de los datos suministrados en los csv. (esto porque se implica cambiar nombre de país o ciudad)

Por lo tanto, ¿es necesario hacer este tipo de correcciones de calidad y coherencia de datos también?

**Comment by arpincheira** [comment]
Hola, el problema que tienes ahí es conceptual. Por lo general el preprocesamiento no está limitado a la eliminación de datos  nulos, truncamientos o errores de titeo o lecturas, sino que este se utiliza para poder adaptar datos "en bruto" con el objetivo de hacerlos mucho más "legibles"/"trabajables" según se requiera. 

Dado esto, es importante destacar que uno de los requisitos de este proyecto es **priorizar la no pérdida de la información entregada**, por lo que partimos de la base de que los datos no se encuentran "malos"(hay un par de casos en los que se presentó un error el que se detalla en la issue #154) sino que se encuentran desordenados. 

Dado lo anterior, la respuesta a tu pregunta es **no** el preprocesamiento que nosostros solicitamos no incluye la corrección de la "coherencia" de lo datos.

**Comment by larryuc** [comment]
Estimado, me queda claro entonces, pero de igual forma entonces internamente quedaran inconsistencias entre aeropuerto, ciudad y paises si asumimos las relaciones que vienen, mas en especifico, no existe ciudad copiapo ni el pais Israel, entonces en la base de datos final se heredaran estas incoherencias de datos,

adjunto imagen
![image](https://user-images.githubusercontent.com/89151219/169377744-96a0b70f-bbdf-4b6e-b473-daa15d191caf.png)

**Comment by arpincheira** [comment]
Lo que mencionas de los nombres de los aeropuertos no influye en lo que respecta al proyecto como tal, simplemente fue una confusión que se dio en los datos entregados, ustedes deben asumir que en ese sentido los datos son correctos.
