### ISSUE TITLE
[Duda de Contenido] Renombrar llave foránea

### ISSUE THREAD

**Issue by aerotecnia99** [IIC2413/Syllabus-2022-1#206]
Hola!
Es posible renombrar una llave foránea en una tabla? 
Por ejemplo, tengo las siguientes entidades:

- Compra(id, Usuario.id, productos)
- Usuario(id, nombre)

Es posible renombrar la llave foránea Usuario.id en Compra? y quedaría tipo "Usuario.cambio_de_nombre" o solo "cambio_de_nombre"?

Gracias :cactus:

**Comment by arpincheira** [comment]
Ojo con subrayar las llaves primarias. En lo que respecta a las llaves foráneas, estas pueden tener el nombre que tu quieras siempre que explicites su naturaleza, la tabla a la que referencia y el atributo de esta al que alude.
