### ISSUE TITLE
[Duda entrega 2 proyecto] GRUPO PAR consulta n°4 

### ISSUE THREAD

**Issue by gonzaloi21** [IIC2413/Syllabus-2022-1#208]
Cuando preguntan por mayor afluencia de pasajeros por aeródromo; ¿se debe tomar como número de pasajeros el máximo de pasajeros por aeronave que llega a cada aeródromo? Pregunto esto porque no hay otro atributo que mide numero de pasajeros...

Mi otra pregunta es que si, para esta consulta, ¿tomamos en consideración solo aquellos vuelos que tengan operacion_id ?(vuelos que serán efectuados si o si). 

Gracias

**Comment by arpincheira** [comment]
Hola, te recomiendo ver las issue #185 y la #202
