### ISSUE TITLE
Error al crear tablas [Entrega 2]

### ISSUE THREAD

**Issue by camibennett** [IIC2413/Syllabus-2022-1#209]
Hola! Estamos tratando de crear las tablas en la base de datos y nos sale el siguiente error al intentar crear una tabla:
ERROR:  there is no unique constraint matching given keys for referenced table
Que significa?

Muchas gracias :)

**Comment by arpincheira** [comment]
Hola, tal como se menciona en el error, el problema ocurre debido a que haces una referencia a un atributo de otra tabla como llave foránea y no añades la restricción de que dicho atributo es único. Aquí te muestro un ejemplo:

```sql
CREATE TABLE foo (
    foo_id INT PRIMARY KEY,
    nombre        VARCHAR(256) NOT NULL
);

CREATE TABLE bar(
    bar_id INT PRIMARY KEY,
    foo_llave_foranea VARCHAR(256) NOT NULL REFERENCES foo(nombre),
);
```

Cómo puedes observar, en el ejemplo descrito existe una llave foránea en la tabla bar que referencia al atributo nombre de la tabla foo, el problema con esto es que, si en foo se añaden 2 datos cuyos nombres sean iguales, la referencia se vuelve incierta, lo que termina generando errores. Para poder solucionar esto debes añadir una UNIQUE constrain, para más información te dejo la [documentación de postgresql](https://www.postgresql.org/docs/14/ddl-constraints.html)
