### ISSUE TITLE
[Duda Entrega 2 IMPAR] Compañías y vuelos

### ISSUE THREAD

**Issue by robertoorrego** [IIC2413/Syllabus-2022-1#210]
Hola! En la tabla vuelos se puede ver que existen aproximadamente 150 vuelos y que cada uno tiene su respectiva compañía, sin embargo, viendo la tabla de trabajadores se puede ver qué múltiples compañías se asocian a un mismo vuelo.  Esto está bien?

Ejemplo: vuelo_id = 19
En la primera imagen se ve un query de la tabla vuelos, donde se identifica cada vuelo_id con una compañía. En la segunda vemos un query de la tabla trabajadores donde se puede ver que el vuelo id se asocia a múltiples compañías.

<img width="387" alt="bbdd 1_1" src="https://user-images.githubusercontent.com/70174581/168910767-2d29f87e-8b7b-49fa-b67b-58124ca3ff22.png">

<img width="1350" alt="bbdd 1_2" src="https://user-images.githubusercontent.com/70174581/168910800-cc09e824-b054-41d2-aac4-5d2222310c26.png">

**Comment by arpincheira** [comment]
Esto ya se contestó en la issue #141. La respuesta es: No hay un error de datos, el problema es que están interpretando cosas incorrectas a partir de los datos debido a que la forma que se utilizó para guardarlos inicialmente no es óptima.
