### ISSUE TITLE
Ruta para importa csv

### ISSUE THREAD

**Issue by Jesusdelgad** [IIC2413/Syllabus-2022-1#211]
Holaa subi mi csv al servidor pero al tratar de poblar mi tabla trabajadores que cree en el servidor me tira:  "No such file or directory", se que es la ruta la cual me esta dando error pero la he cambiado y todavía no puedo solucionarlos

Comando: \COPY trabajadores FROM ’Entrega2/csv/trabajadores.csv’ DELIMITER ’,’ CSV HEADER

![issue](https://user-images.githubusercontent.com/80914510/168919073-5a37cc78-8a27-4a2f-b649-9cf71a2a3a31.png)
![issue 2](https://user-images.githubusercontent.com/80914510/168920276-4628b5c7-6989-4c0c-8407-dda294021cc9.png)

**Comment by arpincheira** [comment]
Hola, resulta ser que estás ocupando un path absoluto, para evitar eso recomiendo usar un path relativo del tipo `./Entrega2/csv/trabajadores.csv` o el absoluto correcto que sería `/home/grupo41/Entrega2/csv/trabajadores.csv`
