### ISSUE TITLE
[Entrega 2] Duda sobre dropdown

### ISSUE THREAD

**Issue by MrBased** [IIC2413/Syllabus-2022-1#212]
¿Este calendario que se despliega para seleccionar fecha cuenta como _dropdown_? (ver imagen). ¿O piden un _dropdown_ más simple?

![image](https://user-images.githubusercontent.com/24458834/168920506-39593c44-302b-4a93-9a13-a43ca9d7f9e3.png)

**Comment by arpincheira** [comment]
Yo creo que eso si cuenta, aunque no hay problema en hacer uno más sencillo.
