### ISSUE TITLE
[Entrega 2] [Impar]

### ISSUE THREAD

**Issue by Jpuc1143** [IIC2413/Syllabus-2022-1#213]
Hola! Para la consulta 4 de impar, cuando se habla de el cliente que haya comprado la mayor cantidad de tickes se refiere a:

- El cliente que haya comprado la mayor cantidad de reservas que contengan un ticket para aquella aerolinea.
- El cliente que haya comprado la mayor cantidad de ticket individuales para aquella aerolinea sin importar cual sea el pasajero.
- El cliente que tenga la mayor cantidad de tickets como pasajero para esa aerolinea.

**Comment by arpincheira** [comment]
El cliente que compra los tickets es aquel que hace la reserva. En base a esto podemos decir que la respuesta como tal a tu pregunta es:

- EL cliente que haya comprado la mayor cantidad de tickets para vuelos de dicha aerolínea.
