### ISSUE TITLE
[Entrega 2] [Grupo Impar] Tabla vuelo con aeronave

### ISSUE THREAD

**Issue by ferperezh** [IIC2413/Syllabus-2022-1#214]
Hola me preguntaba si una aeronave con una ruta determinada establece la velocidad, altitud y valor? . Ya que esto se cumple en toda la tabla de vuelos, menos en esta situación: 
![Captura de Pantalla 2022-05-17 a la(s) 19 33 18](https://user-images.githubusercontent.com/69528837/168929061-9788953a-29ab-4b2b-a63b-f9bf9ceb8271.png)
En donde con el mismo código de aeronave y misma id_ruta tiene distinta velocidad y altitud. Estas son la linea 2 y 105 del archivo entregado pero no se si es una equivocación del excel o esta mal asociado no mas.

**Comment by arpincheira** [comment]
Solo hay un atributo que está relacionado a la aeronave y la ruta, el resto es una coincidencia. No puedo especificar más (hint: ver entrega 1)
