### ISSUE TITLE
[Entrega 2][Par] Consulta de Vuelo con dos FPL

### ISSUE THREAD

**Issue by benitopalaciosm** [IIC2413/Syllabus-2022-1#215]
Hola, ¿Está bien que exista un codigo de vuelo que tenga asociado dos FPL distintos, con fechas distintas? Solo ocurre con el codigo de vuelo KAI2257.

**Comment by arpincheira** [comment]
Es curioso lo que mencionas, a priori no debería generar ningún problema así que puedes suponer que es correcto.
