### ISSUE TITLE
[Entrega 2] Piloto y copiloto

### ISSUE THREAD

**Issue by tocococa** [IIC2413/Syllabus-2022-1#216]
Hola, tengo una duda viendo los datos que entregaron, existen planes de vuelo en que no hay un copiloto asignado, esto a priori me hace sentido (he estado en vuelos regionales en que no hay copiloto) pero para efectos del proyecto no se si se espera que todos los vuelos tengan a un piloto y a un copiloto.

**Comment by arpincheira** [comment]
Un vuelo no puede no tener un piloto, pero puede perfectamente no tener un copiloto asignado en términos de este proyecto.
