### ISSUE TITLE
Duda sobre recorreción C1

### ISSUE THREAD

**Issue by lfb1206** [IIC2413/Syllabus-2022-1#218]
Buenas tardes, queria consultar cuando van a estar más o menos las recorreciones, ya que estas se enviaron hace más de un mes y no se ha dado ningún aviso al respecto.

Muchas gracias de antemano!

**Comment by larryuc** [comment]
Me sumo a esta inquietud.. Cuando entregaran resultado de recorreccion C1? 🙄

**Comment by larryuc** [comment]
Bien! Acabo de revisar y estan recorregidas hoy, muchas gracias!! :)

**Comment by lfb1206** [comment]
Buenas, al parecer solo han recorregido en una sección, dado que a mi no me aparece esta información en la plantilla de notas. 
Ojala puedan resolver esta situación lo antes posible o entregar información acerca de ella.
¡Muchas gracias de antemano!
