### ISSUE TITLE
[Entrega 2] Output y exactitud de queries

### ISSUE THREAD

**Issue by Jpuc1143** [IIC2413/Syllabus-2022-1#220]
Hola! ¿Es posible usar solo un query para hacer todas las consultas del enunciado? Por ejemplo para los grupos impares, se pide que se busque el cliente más frequente, la cantidad y el porcentaje de vuelos aceptados, rechazados, etc. ¿Es valido que la página muestre solo una tabla que tabule los vuelos aceptados, rechazados, totales, porcentajes y cliente más frequente en una sola query?

**Comment by arpincheira** [comment]
Hola, de ser posible, es posible. Ahora, si hablamos de correctitud, esto no sería correcto y probablemente no sea aceptado del todo al momento de hacer la corrección, así que envés de gastar esfuerzos en hacer algo así y arriesgarse a un descuento recomendaría hacer una query por consulta y una mini página principal para poder acceder a los resultados de cada una de estas.

**Comment by Jpuc1143** [comment]
Lo preguntaba porque ya lo habia hecho y me vino la duda despues. Bueno al menos es facil descomponer la query xD
