### ISSUE TITLE
[Entrega 2] Uso de LIKE

### ISSUE THREAD

**Issue by vicentethomas** [IIC2413/Syllabus-2022-1#221]
Hola! Con mi compañero tenemos la duda si además de que sea case_insensitive, las consultas pueden utilizar LIKE para que encuentre valores similares a los que el usuario ponga en el input (por ejemplo si se ingresa LATAM EC, encontrará consultas de LATAM ECUADOR). Esto además permite que si el usuario no se sabe algun input, se puede dejar en blanco y así mostrar todos los resultados posibles para la consulta.
Creemos que así la experiencia del usuario sería mejor...
De antemano muchas gracias!

**Comment by arpincheira** [comment]
Hola, pueden ocupar lo que sea siempre y cuando se haya pasado en clases.
