### ISSUE TITLE
[Entrega 2] Conecion al servidor

### ISSUE THREAD

**Issue by TonioElbuey** [IIC2413/Syllabus-2022-1#222]
Hola,

No puedo establecer ninguna conexión con el servidor. Estoy intentando desactivar el firewall o algo así pero no encuentro el origen del problema. ¿Podría ayudarme?

![Pregunta_2](https://user-images.githubusercontent.com/70761778/169306008-fadd67da-630d-4bac-9db3-564918390edd.PNG)
![Pregunta_2_2](https://user-images.githubusercontent.com/70761778/169306017-e47778d6-e290-4725-8c2a-84b48b08d34f.PNG)

**Comment by arpincheira** [comment]
Hola, revisé su página y en la línea 17 les falta un `;`(semicolon) al finalizar la definición de la variable `query`. También les falta una en la línea 24(al final del echo en el mensaje de error)

**Comment by TonioElbuey** [comment]
Simplemente errores de sintaxis...
Disculpe las molestias, pensé que era un problema de comunicación con el servidor :(

Muchas gracias!
