### ISSUE TITLE
Edad trabajador

### ISSUE THREAD

**Issue by conicorreag** [IIC2413/Syllabus-2022-1#223]
Hola! una pregunta, en la entrega 1 sale que tenemos que guardar la edad de cada trabajador y en los datos que nos entregaron sale la fecha de nacimiento. ¿cual de los dos guardamos en las tablas?
Gracias!

**Comment by arpincheira** [comment]
Hola, el problema de guardar la edad de cada trabajador es que esto puede ser bastante ineficiente ya que sería un dato que quedaría obsoleto cada año y deberían modificarse las tablas de forma continua. Es por eso que se les da la fecha de nacimiento envés de la edad y por lo mismo recomendamos que guarden el primero en las tablas.
