### ISSUE TITLE
[Entrega 2] Resultado de queries cuando hay empate

### ISSUE THREAD

**Issue by negamartin** [IIC2413/Syllabus-2022-1#224]
Hola!

Tengo una duda sobre las queries en que se pide el resultado con mayor cantidad de algo, por ejemplo en el enunciado impar la consulta 6.

Cuando ocurren empates, cuántos resultados se han de devolver? Todos los mayores o sólo 1?

Muchas gracias

**Comment by arpincheira** [comment]
En el caso de haber un empate deben mostrar todos los mayores. De todas formas también se va a admitir el mayor justificando su criterio en base a lo expuesto por el enunciado.
