### ISSUE TITLE
[Entrega2] Servidor E2

### ISSUE THREAD

**Issue by mhrobles** [IIC2413/Syllabus-2022-1#225]
me podrian explicar mejor lo del grupoXXe2 como nuevo servidor? o sea, ahora tendríamos que entrar con 
ssh grupoXXe2@codd.ing.puc.cl ?? y cual sería la contraseña en ese caso? estoy perdido con esto, y estoy preocupado, porque creo que borré las tablas que tenia de la e1 y no se si afectará en algo, porque ahora agregué las nuevas tablas

**Comment by arpincheira** [comment]
Hola, hay un problema de conceptos en lo que mencionas. Esto se debe a que estás confundiendo el usuario del servidor que ustedes poseen con la base de datos que ustedes deben utilizar para la entrega. En primer lugar **el usuario es el mismo de la entrega pasada**, es decir grupoXX@codd.ing.puc.cl

Por otro lado, la base de datos a utilizar es grupoXXe2. Para acceder a ella pueden usar alguna de estas alternativas:

### Alternativa 1

Entrar al servidor y usar el comando `psql`, luego ingresar su contraseña y, una vez hayan ingresado a postgreSQL, usar `\c grupoXXe2`.

Imagen de ejemplo:
![image](https://user-images.githubusercontent.com/37157550/169420082-ccaa3ca8-2d43-4416-b1ee-e62efaa7e6eb.png)

### Alternativa 2

Entrar al servidor y usar el comando `psql grupoXXe2 -U grupoXX`, luego ingresar su contraseña y listo.

Imagen de ejemplo:
![image](https://user-images.githubusercontent.com/37157550/169420303-e20cb289-aa6b-494a-b8a2-76ac8ad47f2f.png)

**Comment by mhrobles** [comment]
aaaa ya, entiendo, y si hice algún cambio en el servidor de la entrega 1, afecta en algo? se puede recuperar lo que tenia antes?

**Comment by arpincheira** [comment]
Hola, no afecta. No estoy 100% seguro de que puedan recuperar dichos datos a priori, igual creo que tienen acceso bloqueado a grupoXXe1 por lo que no deberían poder acceder ni modificarla.
