### ISSUE TITLE
[Entrega 2][Impar] Reservas sin info. de pasajeros

### ISSUE THREAD

**Issue by agucova** [IIC2413/Syllabus-2022-1#227]
Hola,

En nuestra etapa de procesamiento de datos nos dimos cuenta que existían tres entradas en la planilla de reservas donde no hay información sobre el pasajero.

¿Está bien que asumamos que en estos casos el pasajero es igual al reservante, es decir, que es una reserva comprada solo para sí mismo?

**Comment by arpincheira** [comment]
Ya se contestó esto en la issue #154
