### ISSUE TITLE
[Entrega 2][Impar] Potenciales datos erróneos

### ISSUE THREAD

**Issue by agucova** [IIC2413/Syllabus-2022-1#228]
Hola, en relación con los issues #141, #157 y #210, es aceptable que eliminemos datos que parecen violar la integridad referencial del modelo implícito de datos?

Frente a la paradoja planteada en esas issues no pudimos encontrar una solución más allá de eliminar las entradas en `trabajadores.csv` que hacen referencia a vuelos aparentemente inexistentes.

**Comment by arpincheira** [comment]
Hola, creo que no has entendido correctamente las respuestas a las Issues que referencias. La tabla trabajadores no posee vuelos inexistentes, sino que guarda a los trabajadores de una forma poco óptima que tiende a confundir a simple vista(esa es la idea). 

Dado lo anterior, la respuesta a tu pregunta es el siguiente conjunto de preguntas: ¿Están interpretando bien los datos? ¿No será que al borrar los "datos erroneos" pierdan información importante que no están viendo?

Recomiendo que le den un vistazo a los datos y lean nuevamente la issue #141 antes de ir borrando información y no procesarla como tal.
