### ISSUE TITLE
[CONSULTA GRUPO PAR] Vuelos privados y militares pregunta 4

### ISSUE THREAD

**Issue by gitlobo** [IIC2413/Syllabus-2022-1#229]
Holaaa! queremos saber qué hacer con los vuelos privados y militares, ya que estos no se deben incluir en la tabla vuelo.... Por consiguiente, según lo pedido para el modelo, no tenemos acceso a los aerodromos de salida y llegada, ni la fecha de salida ni de llegada. Tomado en consideración que para la afluencia por aerodromo en un bloque horario necesitamos saber cuantos pasajeros llegan o salen de un lugar, y todos los vuelos deberían contar si fueron realizados. Deberíamos hacer una tabla "extra" para los datos faltantes de los vuelos privados y militares o la pregunta se responde solo con la información de los vuelos comerciales (pregunta 4)?
Graciaas ⚡

**Comment by carmebe** [comment]
Hola, si ves los datos (y también el enunciado de la entrega 1), todos los vuelos (comerciales, privados, militares) tienen aeródromos y fechas de salida y llegada. Ahora, con respecto a la consulta de por sí, ya fue respondida: https://github.com/IIC2413/Syllabus-2022-1/issues/185

**Comment by gitlobo** [comment]
Ya la leí y no soluciona mi duda. Según el enunciado de la primera entrega, una propuesta de vuelo es la que tiene las fechas y los aerodromos y estas son solo de vuelos comerciales. Por otro lado, en fpl se registran los vuelos de todos los tipos, pero no estos no poseen fechas ni aerodromos.

**Comment by carmebe** [comment]
![img](https://user-images.githubusercontent.com/80768993/169620657-58e759c3-80fd-4f43-9e71-56665fd1d0d7.PNG)
Estos "mismos datos" son los de una propuesta de vuelo.

**Comment by emolaba** [comment]
Perfect @carmebe, muchas gracias por la ayuda! 👍🏼
