### ISSUE TITLE
Control 1 - Algebra relacional completa

### ISSUE THREAD

**Issue by larryuc** [IIC2413/Syllabus-2022-1#23]
Estimados,
En el presente control 1, se puede utilizar el operador agrupar y division?
Adicionalmente se puede incluir el uso de la funcion count() que si es ANSI SQL?

```
División (/) (Cociente)
Supongamos que tenemos dos relaciones A(x, y) y B(y) donde el dominio de y en A y B, es el mismo.

El operador división A / B retorna todos los valores de x tales que para todo valor y en B existe una tupla {\displaystyle \langle x,y\rangle }{\displaystyle \langle x,y\rangle } en A.

Agrupación (Ģ) (Unión)
Permite agrupar conjuntos de valores en función de un campo determinado y hacer operaciones con otros campos.
```

info: https://es.wikipedia.org/wiki/%C3%81lgebra_relacional

**Comment by larryuc** [comment]
Que pasa tambien con el order by? se puede utilizar el operador τ?

**Comment by matiastoro** [comment]
No, solo se puede usar lo visto en clase.
DIvisión se puede definir en base a operadores vistos.
No se puede agrupar en algebra relacional.
