### ISSUE TITLE
[Entrega 2] Problema con Pilotos/Copilotos y licencias asociadas

### ISSUE THREAD

**Issue by aerotecnia99** [IIC2413/Syllabus-2022-1#230]
Hola! 
Al filtrar los .csv entregados nos percatamos que ocurre una anomalía en pilotos/copilotos y su licencia asociada, ya que encontramos que un co/piloto tiene asociada 1 o más `licencia_actual_id`. Nos gustaría entender el contexto que justifica esta multiplicidad y si es correcto o no que esto ocurra, pues de serlo o no tendríamos que adaptar nuestro esquema o filtrar de otra manera los datos (eliminando filas).

Salu2 :cactus:

**Comment by arpincheira** [comment]
Hola, puede pasar debido a que cada una de estas licencias corresponde a un permiso distinto que puede tener un piloto y que a su vez puede estar activo de forma contemporánea con otros, por ejemplo, un piloto puede tener una licencia comercial, una privada y una militar. Algo similar se da con los distintos tipos de licencias de conducir en las que un individuo puede tener una licencia de moto, de automóvil y una de vehículos de carga.

**Comment by aerotecnia99** [comment]
Cual es la referencia de la que haces mención?

**Comment by arpincheira** [comment]
Al id de la licencia

**Comment by aerotecnia99** [comment]
@arpincheira y este `id_licencia` es único? por ejemplo `id_licencia = 47` siempre será licencia comercial.

**Comment by arpincheira** [comment]
Hola, no se exactamente si esa licencia sería comercial(para eso habría que ver los datos de los grupos pares). Pero ese id sería único.
