### ISSUE TITLE
[Entrega 2] impar / Consulta para clientes 

### ISSUE THREAD

**Issue by larryuc** [IIC2413/Syllabus-2022-1#231]
Buenas tardes,
Una consulta, en el enunciado dice:
![image](https://user-images.githubusercontent.com/89151219/169627050-26cdddd9-557d-4e87-a856-bb95e34695c4.png)

Sabemos que por cliente, tenemos cliente comprador, y cliente pasajero, se asume que es para el comprador?
Y que pasa si hay un cliente para la misma aerolinea que tiene la misma cantidad de compras? vale decir hay un empate, se deben mostrar ambos o mas clientes en empate, o basta con mostrar solo uno de ellos?

Esperamos su respuesta, Gracias!

**Comment by arpincheira** [comment]
Hola, esa pregunta fue más o menos contestada antes en las Issues #123 y #224, por si les quieres dar un vistazo.
