### ISSUE TITLE
Duda archivos servidor

### ISSUE THREAD

**Issue by Gau04** [IIC2413/Syllabus-2022-1#233]
Hola! Estoy trabajando con el server como repositorio de github y al momento de añadir la carpeta Sites olvidé crear un .gitignore con los archivos del server (.bashhistory, .bashlogout, .psql_history, etc.), por lo que quedaron en el repositorio. Me gustaria saber si existe alguna manera de eliminar estos archivos del repositorio sin eliminarlos del server, y evitar asi cometer errores fatales para la entrega :( .

**Comment by arpincheira** [comment]
Hola, lo que debes hacer es identificar esos archivos, añadirlos a tu `.gitignore` y luego eliminarlos con:

`git rm --cached filename.fileextension`(Si quieres eliminar un archivo)
`git rm --cached -rf directoryname`(Si quieres eliminar una carpeta)

Si quieres verificar que este comando puedes hacer un `git status`(ver que se vaya a borrar del repositorio) y `ls`(ver que no se borre del sv) antes de commitear y pushear tus cambios.
