### ISSUE TITLE
Error conexión al servidor

### ISSUE THREAD

**Issue by arturoprietovic** [IIC2413/Syllabus-2022-1#235]
Hola, hemos tratado mucho de encontrar errores de sintaxis, pero sigue sin funcionar la la conexión.
![image](https://user-images.githubusercontent.com/65640660/169889129-b573babc-de52-426c-b1e2-b172ae0c202c.png)

Probando sabemos que las variables de data.php si llegan hasta la consulta pero $db no está funcionando.
grupo126

**Comment by matiastoro** [comment]
Hola,
Estaban haciendo 

echo "hola: $db";

y esa linea les estaba produciendo un error porque $db no sabe como imprimirse.
Saqué esa linea y veo que si está funcionando la conexión.

**Comment by arturoprietovic** [comment]
graciaas :)
