### ISSUE TITLE
[Entrega 1] Duda sobre sección "formato de entrega"

### ISSUE THREAD

**Issue by Dafnemami** [IIC2413/Syllabus-2022-1#26]
![imagen_2022-03-26_115541](https://user-images.githubusercontent.com/53848830/160245014-84ac3221-204c-4067-83e1-77bd7e880213.png)

Sobre la imagen anterior, me queda la duda sobre los puntos encerrados en azul. En conjunto ambos me dan a entender que el esquema (aka el dibujo de las tablas) debe ser capaz de soportar todas las consultas, y que a su vez solo debemos crear y subir al servidor solo las tablas que permitan responder a las primeras 3 consultas.

Tenemos la duda si es que el último punto está erróneo, i.e. debemos subir al servidor las tablas necesarias para responder solo las 3 primeras consultas o todas?

:)

**Comment by arpincheira** [comment]
Hola, en primer lugar el esquema no es un dibujo de las tablas, sino que es una declaración de la estructura de las mismas, por ejemplo un Cuadro podría tener un esquema parecido a este:

`Cuadro( <ins>id</ins> int, fecha_de_creación  date,  nombre varchar, id_autor int, etc.... )`

Ahora, en lo que respecta a tu pregunta, la idea es que ustedes declaren en su esquema todas las posibles entidades que pueden identificar en el enunciado con sus respectivos atributos, considerando datos que se encuentren explícitos en la descripción del problema como aquellos que (hint) **se encuentren implícitos en alguna de las consultas que deben responder**. Por ejemplo, si es que en el caso del cuadro la descripción del problema menciona que tiene fecha de creación, un identificador, un nombre y un autor asociado pero les preguntan en la consulta 4 por la ubicación en la que se encuentran dichos cuadros, ustedes pueden inferir que en el esquema el cuadro debe tener una dirección asociada y por ende se espera que también la declaren en el esquema.

Ahora, ¿Qué es lo que deben subir al servidor  en el caso anterior? Si bien no es necesario que suban la tabla de ubicaciones(en el caso de existir una) si deben subir la tabla Cuadro y esta debe ser coherente con aquella declarada en el esquema que presentan(es decir, debe tener algún atributo que referencie a las ubicaciones en el caso de que esta sea una tabla aparte).

En resumen:
- En el esquema deben declarar todas las tablas y sus atributos necesarios para responder la **totalidad** de las consultas.
- En el servidor deben subir y poblar las tablas necesarias para responder las primeras 3 consultas y estas **deben ser idénticas** a las que declararon arriba.

Aclarando esto último, si yo declaro:
 
`
Cuadro( <ins>id</ins> int, fecha_de_creación  date,  nombre varchar, id_autor int, ubicación_id int)
Ubicación(<ins>id</ins> int, nombre)
`

pero no necesito Ubicación, entonces **solo debo subir al servidor la tabla Cuadro**.  Aunque pueden subir la otra para evitar posibles problemas

***disclaimer:** _El ejemplo mostrado anteriormente no necesariamente corresponde a la modelación de una base de datos real, solo es un  ejemplo de juguete utilizado con la finalidad de contestar la pregunta y por ende no se puede asegurar la correctitud del modelo presentado en lo que respecta a buenas prácticas de desarrollo ni normalización de una base de datos_

**Comment by ignaciaurrutia** [comment]
¿Hola, qué significa esta parte _<ins>id</ins> int_ cuando se declara la estructura de Cuadro? Entiendo que id se define como int, pero ¿las cosas que están antes y después de id son para definir que es la llave?
