### ISSUE TITLE
[Entrega 1] Duda sobre unicidad de atributos

### ISSUE THREAD

**Issue by fagiannoni** [IIC2413/Syllabus-2022-1#27]
¡Hola!👋  Modelando en papel las tablas requeridas según lo pedido en el enunciado (la parte _Impar_) me entró la duda sobre si algunos atributos son únicos o no. Para esto quería saber si puedo asumir lo siguiente:
1. El código de una _Compañía aérea_ **si** se puede repetir entre distintas compañías.
2. El número de pasaporte **no** se puede repetir entre distintas personas (independiente de donde trabaja).
3. El código IATA **no** es único, pero el código ICAO **si** es único (esto es lo que encontré en internet, pero me pareció entender algo ligeramente distinto del enunciado).

¡Muchas gracias desde ya! 😄
Saludos

**Comment by matiastoro** [comment]
Pueden asumir que:
1. el código de una compañia no se puede repetir.
2. El número de pasaporte no se puede repetir.
3. El código IATA es único.
