### ISSUE TITLE
[Entrega 1] Duda sobre Data Types

### ISSUE THREAD

**Issue by JorgeGuzz** [IIC2413/Syllabus-2022-1#28]
Holaa! Estuve investigando un poco por internet y parece que postgresql soporta arrays, entonces queria saber si es valido ocuparlos a la hora de realizar nuestra modelación y de paso preguntar que otros Data Types son aceptables. 

![imagen](https://user-images.githubusercontent.com/80768853/160301518-a418dcdc-ece0-4db6-93bb-521009a9a4f9.png)

Saludos y gracias de antemano 😄

**Comment by matiastoro** [comment]
No pueden usar arrays.
Pueden usar Boolean, Integer, Varchar, Char, Date, TImestamp, Time, Float, Text, Serial (es in integer por debajo).
