### ISSUE TITLE
Evaluación de Pares E2

### ISSUE THREAD

**Issue by kunafuego** [IIC2413/Syllabus-2022-1#280]
Hola! Quería realizar la Evaluación de Pares de la entrega 2 pero el form ya estaba cerrado. En un anuncio se especificó que el plazo era hasta el 9 de junio! Por si lo podrían revisar.

Gracias

**Comment by arpincheira** [comment]
Hola, lamento mucho que se haya cerrado antes de lo indicado, ahora se encuentra habilitado nuevamente(lo mantendremos así hasta el próximo lunes), saludos.
