### ISSUE TITLE
Guia 1 - g y h

### ISSUE THREAD

**Issue by Piolawa** [IIC2413/Syllabus-2022-1#3]
Hola!
g) logro obtener todos los colores que hay pero no se como relacionar todos los colores a un solo jugador. Algún hint?

h) 
![1647479938460848466731726143107](https://user-images.githubusercontent.com/80898544/158717856-6942a10a-6196-44d5-913b-e7775e30a4a3.jpg)
 Es asi??? Tengo muchas dudas en ese ejercicio

Saludos!

**Comment by matiastoro** [comment]
Hola,
g) Que pasa si cruzas todos los colores con todos los jugadores? que te da? Puedes restarle algo a ese conjunto?

h) - Al join le falta una condición. Piensa cuales son todos los atributos de la llave de Juego.
- Puedes hacer lo mismo sin necesidad de hacer ese join, ya que si en la partida eres impostor y estas muerto puedes asumir que perdiste (si asumimos tambien que hay solo 1 impostor).
- Te falta el nombre de los jugadores.
