### ISSUE TITLE
[Entrega 1] Duda con uso de inglés en la entrega

### ISSUE THREAD

**Issue by SCarcG1** [IIC2413/Syllabus-2022-1#31]
Hola, ¿existe alguna limitación con el uso de Inglés para hacer el esquema de tablas con sus atributos, estando todos estos en inglés?

**Comment by arpincheira** [comment]
Hola, si bien no existe un descuento asociado a esto, yo te recomiendo que en el informe añadas un apartado en donde añadas la traducción realizada con el objetivo de evitar problemas al momento de realizar la corrección. De todas formas, en el caso de que no quieras realizar dicha traducción te invito a escribir el nombre en español omitiendo tildes y eñes, considerando que los nombres que contengan espacios los pueden remplazar con snake_case.
