### ISSUE TITLE
Dudas con tercera consulta-Grupos impares

### ISSUE THREAD

**Issue by SCarcG1** [IIC2413/Syllabus-2022-1#32]
Hola, tengo una duda con esta consulta, ya que nos piden las rutas mas usadas por los vuelos. ¿Se asume que es solo aquel que es mas usada o una lista en orden de mas usado a menos usado?

**Comment by matiastoro** [comment]
Vamos a cambiar la pregunta 3 por otra, ya que no se puede resolver usando algebra relacional.
Se puede resolver con SQL y se pide la o las rutas mas voladas en caso de haber empate.

**Comment by namadatzis** [comment]
Hola! El enunciado sigue igual, se hará el cambio?
