### ISSUE TITLE
contenido próximo control

### ISSUE THREAD

**Issue by santiago3c** [IIC2413/Syllabus-2022-1#347]
hola, escribo para preguntar un par de cosas respecto al próximo control:
1. los contenidos que serán evaluados serán los de las clases 5, 6 y 8?
2. hay que llegar con algo instalado para el control, y en qué programa se va a hacer el control?
3. van a haber preguntas de psycopg en el control?

**Comment by arpincheira** [comment]
Hola, este repositorio corresponde al primer semestre del 2022.  Te recomiendo hacer tu issue [aquí](https://github.com/IIC2413/Syllabus-2024-1/issues). Éxito en el control igual
