### ISSUE TITLE
Dudas E1 

### ISSUE THREAD

**Issue by Martinrsts** [IIC2413/Syllabus-2022-1#35]
Hola,
En el enunciado para grupos pares,

¿Una operación tiene pista y puerto de embarque para salida y entrada o para salida o entrada?
En el enunciado dice: "Un vuelo representa una propuesta de viaje entre dos aeródromos enviado por una
compañía aérea con 1 mes de antelación", pero nos piden en la segunda consulta "Muestre todos los vuelos que no fueron planificados por alguna compañía aérea". ¿Se refieren en la consulta a los vuelos sin FPL?

Gracias!

**Comment by matiastoro** [comment]
Una operacion representa ya sea un despegue a una llegada.
Un plan de vuelo esta asociado a dos operaciones: una de despegue y una de llegada
Cada operacion (tanto de llegada como de salida) tiene asociado una pista y puerto de embarque.

"Muestre todos los vuelos que no fueron planificados por alguna compañía aérea" esta medio confuso. Se refiere a los FPL que no tienen un vuelo asociado. De todas maneras si entienden lo segundo esta bien, mientras expliquen que entendieron.

**Comment by gitlobo** [comment]
Asumimos que todo vuelo comercial va a estar asociado a un FPL y un NO comercial y militar no? o solo NO comercial?
graciasss :)

**Comment by gitlobo** [comment]
Gracias :)) <33
