### ISSUE TITLE
[Entrega1] Duda sobre correspondencia de pilotos y tripulantes

### ISSUE THREAD

**Issue by angegazitua** [IIC2413/Syllabus-2022-1#37]
¡Hola! Teníamos una duda sobre los pilotos y los tripulantes. ¿Estos pueden pertenecer a más de una compañía aérea o son exclusivos?

**Comment by matiastoro** [comment]
Pueden asumir que una persona puede trabajar como piloto o tripulacion en 1 o mas compañía aérea. 
Recuerden que pueden agregar cualquier supuesto extra en la entrega.
