### ISSUE TITLE
[Entrega 1] Duda con el soporte de consultas para base de datos

### ISSUE THREAD

**Issue by SCarcG1** [IIC2413/Syllabus-2022-1#38]
Hola, tengo una duda con el soporte de consultas. El pdf menciona que la base de datos debe soportar cada consulta, pero estas incluyen solo las preguntas en SQL, o ¿tenemos que ser capaz de hacer las seis también en algebra relacional?

**Comment by arpincheira** [comment]
Hola, el esquema debe ser capaz de soportar las 6 consultas. Por otro lado, las tablas y los datos a subir en la BDD son solo aquellos que correspondan a las primeras 3 de tu tipo de grupo.  En lo que respecta a realizar las 6 consultas en álgebra relacional, esto no necesariamente es posible, pero de todas formas debes considerar  que tu esquema **debe** contener toda la info relacionada a estas, para más información sobre esto te recomiendo ver la issue #26
