### ISSUE TITLE
Fecha de Entrega 1

### ISSUE THREAD

**Issue by larryuc** [IIC2413/Syllabus-2022-1#40]
Estimados en el PDF publicado dice: 
"Todo esto debe ser realizado antes del viernes 7 de abril a las 23:59"

Viendo el calendario el Viernes es 8 de abril, ¿entonces corresponde a ese viernes la fecha limite de entrega?

Link del PDF Entrega 1: https://github.com/IIC2413/Syllabus-2022-1/blob/main/Proyecto/Entrega%201/Entrega%20I.pdf

**Comment by arpincheira** [comment]
Hola, efectivamente nos referíamos al Viernes 8 de abril
