### ISSUE TITLE
[Entrega 1] Data Types en el Esquema

### ISSUE THREAD

**Issue by Jpuc1143** [IIC2413/Syllabus-2022-1#41]
Hola! Al hacer el esquema, ¿hay que poner el data types de los atributos? Y si es así, ¿hay que usar los que se usan en Postgres (string vs VARCHAR)?

Muchas gracias!

**Comment by arpincheira** [comment]
Si bien en esta entrega no se va a evaluar la correctitud del esquema (solo atingencia al problema presentado), normalmente se debe utilizar VARCHAR y no string.
