### ISSUE TITLE
Duda vuelos NO comerciales y militares

### ISSUE THREAD

**Issue by gitlobo** [IIC2413/Syllabus-2022-1#42]
Si los vuelos NO comerciales y militares no están en la tabla "vuelo" , qué código se les asigna?

**Comment by matiastoro** [comment]
Un nombre de fantasía o la matrícula de la nave

**Comment by jsilvalavin** [comment]
pregunta si fpl tiene la informacion de vuelo, significa que tiene una compañía asociada. Este tambine se rellena con algo de fantasía? puedo confiar que no será una compañía real?
