### ISSUE TITLE
Problema con carpetas en el servidor

### ISSUE THREAD

**Issue by ivannateresa** [IIC2413/Syllabus-2022-1#43]
Hola! :D

Con mi compañera de grupo tratamos de crear una carpeta con el nombre de entrega1, sin embargo, creo que se sobrescribió algo y al abrirlo quedo de la siguiente manera (foto). ¿como lo elimino?.
<img width="658" alt="image" src="https://user-images.githubusercontent.com/69605531/160943761-5c4817dd-34af-4c2b-9a11-28f0089149a6.png">

<img width="365" alt="image" src="https://user-images.githubusercontent.com/69605531/160943719-2ddf96ea-047f-406b-b115-b5ee8f480511.png">

De antemano muchas gracias

**Comment by arpincheira** [comment]
Hola, a decir verdad no me queda del todo claro lo que aparece en la foto, si quieres puedes describir un poco más tu error o directamente enviar un email a arpincheira@uc.cl para hacer un seguimiento más específico de tu problema.

**Comment by Daniel-SebastianGaete** [comment]
Según yo quedó un repositorio dentro de otro. El ícono de la primera imagen es el que sale en esos casos. Si es el caso, en la carpeta que no quieres que sea repositorio de Github debes hacer `rm -rf .git` y dejará de ser un repositorio de Github
