### ISSUE TITLE
Uso de `point`

### ISSUE THREAD

**Issue by agucova** [IIC2413/Syllabus-2022-1#44]
Hola, quería saber si se puede utilizar el [tipo nativo](https://www.postgresql.org/docs/9.1/datatype-geometric.html) `point` de PostgreSQL que describe posiciones para almacenar puntos.

Es más limpio que guardar latitud y longitud por separado (equivale a una tupla (float8, float8), y creo que es la forma más natural de implementarlo con Postgres sin tener [PostGIS](https://postgis.net/).

**Comment by agucova** [comment]
Entiendo. Y con el posible riesgo de pedir mucho, puedo usar el [tipo](https://www.postgresql.org/docs/current/datatype-money.html) `monetary` para costo? (La gracia siendo precisión fraccional fija y output bonito)

**Comment by cadaeic314** [comment]
Sería idea usar el tipo `numeric` en ese caso, el tipo `money` si bien tiene esa función específica en postgresql, es particular de esta implementación de sql y se busca el uso de tipos de datos generales para cualquier implementación en el esquema inicial. Incluso la documentación de postgresql no lo recomienda

![imagen](https://user-images.githubusercontent.com/63424544/160968806-fabec978-4570-4916-834f-a3d1b347831f.png)

**Comment by agucova** [comment]
Resulta que `money` fue deprecado en 8.2 pero después de cambios en la implementación [fue de-deprecado en la versión 8.3](https://www.postgresql.org/message-id/20080526200508.GO21327%40commandprompt.com), por lo que es considerado funcionalidad estándar en PostgreSQL 14.

En todo caso creo que por portabilidad tiene más sentido solo utilizarlo para propósito de formatos usando `cast(var as money)`.
