### ISSUE TITLE
[Entrega 1] Duda sobre vuelos impares

### ISSUE THREAD

**Issue by ignacio-quera** [IIC2413/Syllabus-2022-1#45]
En el enunciado dice que los vuelos indican el aerodromo de salida y llegada. Existe alguna restricción de como representamos el aerodromo en la relación o tenemos que utilizar algo específico como el nombre o el código IATA?

**Comment by matiastoro** [comment]
Pueden utilizar algo que identifique únicamente a un aeródromo, como el id, el codigo oaci o iata
