### ISSUE TITLE
Duda sobre la velocidad y altitud de una aeronave

### ISSUE THREAD

**Issue by drcid98** [IIC2413/Syllabus-2022-1#47]
Hola! ¿puedo asumir que una nave tendrá siempre una misma velocidad y altitud de vuelo?

**Comment by matiastoro** [comment]
Si, puedes asumir que es el promedio.

**Comment by drcid98** [comment]
Creo que no se entendió, me refiero a que si a una nave (un modelo específico) tiene la misma velocidad y altitud sin importar que ruta o destino tenga

**Comment by matiastoro** [comment]
Una aeronave no tiene velocidad y altitud. 
Una operación/FPL/vuelo si.
