### ISSUE TITLE
Duda sobre rutas 

### ISSUE THREAD

**Issue by gvfigueroa** [IIC2413/Syllabus-2022-1#48]
Hola! No entiendo a que se refiere con que las rutas sean listas ordenadas de puntos. Se refiere a que cada ruta incluye cada coordenada por la que pase? o que son ciudades? o que?

**Comment by CarlotaAContreras** [comment]
Hola, buenas tardes. Puedo hacer el supuesto de que la ruta solo tenga los puntos (el de llegada y el de salida)? También me preguntaba como se puede definir el costo según la ruta y el peso, si la ruta es una lista ordenada de puntos. Estoy confundida en esa parte. Me ayudaría que se esclareciera el tema de rutas y puntos porfavor :(
Saludos
