### ISSUE TITLE
Duda sobre inicialización del repositorio en el servidor

### ISSUE THREAD

**Issue by simonmb12** [IIC2413/Syllabus-2022-1#49]
Hola!
Hice un repositorio, y trate de hacer la inicialización con el servidor, pero en la mitad me di cuenta de que no lo había hecho bien, por lo que borre el repositorio y hice uno bien. El problema es que cuando trate de inicializar el repositorio nuevo, me aparece que el servidor ya tiene el repositorio antiguo conectado. No sé como arreglarlo.

**Comment by arpincheira** [comment]
Hola @simonmb12, para poder volver a empezar "desde 0" debes borrar la carpeta oculta `.git`, para ello te recomiendo usar el comando `rm -rf .git` y luego el comando `ls -a` con el objetivo de ver que haya funcionado(la idea es verificar que no aparezca la carpeta .git al usar el último comando)

**Comment by simonmb12** [comment]
eso lo hago desde mi usuario en el servidor verdad?

**Comment by arpincheira** [comment]
Si

**Comment by simonmb12** [comment]
Ahí lo arregle. Otra pregunta que tengo es que cuando hago "git full origin master" me pide un usuario y contraseña de GitHub, pero en el video explicativo no pasa eso.

**Comment by arpincheira** [comment]
Hola, te referías a `git pull origin master`? De ser así te va a pedir la autenticación de tu usuario, para esto el usuario y la contraseña. Ahora, es importante destacar que hoy en día las políticas de privacidad de github son diferentes por lo que la autentificación no requiere realmente tu contraseña sino que un token de github, para más detalles te recomiendo ver la respuesta de la issue #29. Cualquier problema me avisas por aquí.
