### ISSUE TITLE
[Entrega 1] Database donde hacer la entrega

### ISSUE THREAD

**Issue by Jpuc1143** [IIC2413/Syllabus-2022-1#50]
Hola! 
Nos dimos cuenta con mi grupo que tenemos acesso a dos bases de datos: grupo23 y grupo23e1. El enunciado ni la wiki no menciona en cual entregar el proyecto, pero en la ayudantia dice que hay que conectarse a grupo23e1. ¿Cual db hay que conectarse para la entrega, o no importa?

**Comment by arpincheira** [comment]
Hola, la base de datos en donde deben realizar la entrega es grupoXXe1, en su caso sería grupo23e1. Saludos
