### ISSUE TITLE
Desde donde trabajar

### ISSUE THREAD

**Issue by simonmb12** [IIC2413/Syllabus-2022-1#52]
Hola,
Con mi compañero no entendemos desde donde se trabaja para la tarea. Entiendo que hay que trabajar en Postgres, pero eso sería trabajar desde el mismo servidor, por lo que el repositorio de GitHub no serviría, o me equivoco? Si me pueden explicar desde donde trabajar se los agradecería.

**Comment by Kevinnevik** [comment]
Hola, el repositorio de github ustedes lo pueden conectar con el servidor ssh, en la que ustedes pueden subir su material al repositorio y desde el servidor ssh, deben hacer git pull para traer todos los archivos del repo a su servidor. Otra forma es utilizar filezilla.

**Comment by simonmb12** [comment]
Eso lo entiendo bien. Mi problema es dónde trabajar las consultas y tablas de SQL.

**Comment by Kevinnevik** [comment]
en el servidor de su grupo deben colocar el comando psql, entran a la consola de postgres y desde ahí pueden trabajar. Para salirse de la consola postgres deben colocar \q.

**Comment by Jesusdelgad** [comment]
Es primera vez que trabajo con psql y tengo una consulta en eso , la base de datos se estara actualizando cosntantemente en el servidor? , o hay que hacer un "push desde psql"

**Comment by Kevinnevik** [comment]
No es necesario hacer push ni pull en postgres. Sin embargo en el servidor ssh si se necesita hacer pull si es que estas usando un repo en github.

**Comment by Jesusdelgad** [comment]
Claro comprendo , entonces por ejemplo si yo creo que una tabla en el servidor , mi compañera podra ver dicha tabla no?

**Comment by Kevinnevik** [comment]
Si es correcto, tu compañera puede ver dicha tabla

**Comment by simonmb12** [comment]
Las tablas y consultas trabajadas en psql se guardan inmediatamente en el servidor pero en que carpeta? Si yo subo una carpeta desde GitHub con la parte de pdf, luego donde se guarda lo que vaya agregando por psql?
