### ISSUE TITLE
Subir los datos mediante copy a la base de datos

### ISSUE THREAD

**Issue by fsazo** [IIC2413/Syllabus-2022-1#53]
Hola! Tengo una duda sobre donde dejar los archivos csv (donde tengo mis datos) para poder usar el comando copy y subirlo a la base de datos. 

\COPY users (columna_names)
FROM ‘relative/path/to/file.csv’
DELIMITER ‘,’ CSV HEADER;

Queríamos usar este código y no sabemos desde donde comienza el path relativo.
Gracias de antemano.

**Comment by arpincheira** [comment]
Hoa, el path relativo comienza desde el lugar en donde ejecutaste el comando `psql`. Esto quiere decir que, si entras al servidor y quieres hacer `COPY` de un archivo `dummy.csv` que se encuentra en a carpeta Entrega1 puedes hacer dos cosas:
- Ingresar al interior de la carpeta con el commando `cd Entrega1` y desde ahí usar `psql -d grupoXXe1`(donde XX es tu número de grupo). Una vez en PostgreSQL puedes usar `COPY` con el path `./dummy.csv`. 
- Al entrar el servidor usar `psql -d grupoXXe1`(donde XX es tu número de grupo). Una vez en PostgreSQL puedes usar `COPY` con el path `./Entrega1/dummy.csv`.

**Comment by fsazo** [comment]
Gracias!
