### ISSUE TITLE
[Entrega 1] Uso de Github

### ISSUE THREAD

**Issue by Dafnemami** [IIC2413/Syllabus-2022-1#55]
Hola!,

Con mi grupo tenemos la duda sobre para qué destinar el uso de git hub. Tenemos pensado trabajar con archivos .csv y subirlos allí. Por el momento, no vemos nada más allá que haya que subir en dicha plataforma.

Estamos en lo correcto o hay otra cosa para la cual el uso de la plataforma nos es util y no lo estamos viendo?

Saludos cordiales!

**Comment by Kevinnevik** [comment]
Ustedes pueden usar el repositorio de github para conectarlo con el  servidor ssh, entonces pueden subir su material al repositorio y solo deben actualizar con git pull en el servidor y tendrán los mismos archivos que el repo

**Comment by Kevinnevik** [comment]
Este link es de la ayudantía del semestre pasado la cual te puede servir
https://drive.google.com/file/d/1YfUwCyPGpIbpUx8OJaoI5t1wyayJS7WX/view
