### ISSUE TITLE
[Entrega 1] Duda sobre formato Rutas.

### ISSUE THREAD

**Issue by 0DASAC** [IIC2413/Syllabus-2022-1#56]
Hola, en el enunciado dice que "Una ruta, es una lista ordenada de puntos." sin embargo no me queda claro cual es el formato para crear una lista ordenada de elementos en una tabla. (debemos agregar todos los puntos separados por comas?)

**Comment by Daniel-SebastianGaete** [comment]
Hola. El formato queda a criterio de ustedes ya que hay varias implementaciones posibles para modelar una lista ordenada. Lo importante es que a la hora de realizar las consultas se muestre la información de manera correcta y consistente. Si quieres presentar la información como una lista separada por comas, te recomiendo investigar la función `STRING_AGG()` de SQL. Saludos.

**Comment by diegocostares** [comment]
Hola @Daniel-SebastianGaete en ese caso la ruta que tipo de datos tendría? ¿Un varchar o un text?

**Comment by Daniel-SebastianGaete** [comment]
En general como la ruta es una lista ordenada de puntos, los datos que tendría la ruta serían los mismos de los puntos. En particular la función `STRING_AGG()` no retorna nada, solamente permite mostrar el resultado de una consulta de una manera más cómoda.
No sé si respondo tu pregunta, así que quedo atento a tu retroalimentación.

**Comment by diegocostares** [comment]
No entendí muy bien, a que te refieres con "los datos que tendría la ruta serían los mismos de los puntos".
Y para hacer está lista de puntos, ¿tenemos que pasarlo como text?
