### ISSUE TITLE
Pagina web no conecta con BDD

### ISSUE THREAD

**Issue by kraksiplus** [IIC2413/Syllabus-2022-1#58]
Hola, basicamente esta issue es debido a que tengo la pagina lista pero los mis archivos conection.php no estan encontrando la base de datos con la que trabajar a pesar de poner $user, $databaseName y $password de forma correcta, ¿alguna orientacion de como trabajar al respecto?

**Comment by arpincheira** [comment]
Hola, no entiendo a que te refieres con "tener la página lista". En esta entrega no deben entregar una página web, solo un informe (`.pdf`) y tablas en el servidor

**Comment by kraksiplus** [comment]
ooh, perdon, mala mia entonces jaja. Como di el ramo el semestre pasado asumí que la tarea seria la misma con PHP. Error de mi parte. Cuidate :D
