### ISSUE TITLE
Duda enunciado

### ISSUE THREAD

**Issue by Jesusdelgad** [IIC2413/Syllabus-2022-1#59]
No entiendo esta parte del enunciado, porque habla de lenguaje relacional y SQL por separado y no entiendo porque solo hablan de las 3 primeras consultas y no de las restantes. Ojala si me puedes explicar esta parte del enunciado de manera más explicita, porfavor.

○ Las tres primeras consultas solicitadas dependiendo si su grupo es par o
impar en álgebra relacional.
○ Las tres primeras consultas que correspondan a tu grupo, según el
enunciado, en SQL.

PD: Soy de un grupo impar.

**Comment by Daniel-SebastianGaete** [comment]
Hola. Resulta que en el PDF basta con que escriban las tres primeras consultas en álgebra relacional y en SQL. Sin embargo, el esquema debe soportar todas las consultas. Es buen ejercicio que hagan las otras tres consultas, para asegurarse que el esquema funcione, pero no es necesario que lo pongan en el PDF.
Saludos

**Comment by Jesusdelgad** [comment]
Osea ustedes probaran las 6 consultas y deben funcionar , pero nosotros en nuestro pdf basta con que solo explicitemos en algebral racional y en SQL las 3 primeras consultas y no las 6. 

Una consulta pequeña respecto a las consultas, utilzar psql desde el servidor es para ir probando o ustedes revisaran desde ahi el SQL o solo revisaran el pdf?

**Comment by arpincheira** [comment]
Hola, tal y como menciona @Daniel-SebastianGaete , la idea de esta entrega es que podamos evaluar su capacidad de plantear una hipotética base de datos a partir del levantamiento de requerimientos que se pueden obtener del enunciado. Es por esto que se les solicita hacer también 3 de las 6 consultas planteadas tanto en álgebra relacional como en SQL pues les permite tanto a ustedes como a nosotros verificar hasta cierto punto que aquello que plantean es realmente factible o si posee uno que otro error de concepto(pues de existir algo así las consultas no se podría hacer), además de mostrarles que la gracia del álgebra relacional es presentar una base lógica sobre la cual se plantean las consultas a los distintos lenguajes de consulta/adminstración de bases de datos (sobretodo para los relacionales como SQL).

**Comment by arpincheira** [comment]
Con respecto a tus preguntas:

- nosotros tenemos un mínimo de requisitos que deben tener en sus esquemas para poder contestar dichas consultas. 
- Sí, basta que expliciten las primeras 3 tanto en SQL como en álgebra relacional
- Nosotros  evaluaremos las consultas en temas de funcionalidad y correctitud([ver la rúbrica de la entrega](https://github.com/IIC2413/Syllabus-2022-1/tree/main/Proyecto/Entrega%201)). Por lo que si probaremos las de SQL en el servidor(deben funcionar con las tablas y datos que hayan subido)
- También revisaremos las consultas del pdf en temas de correctitud, considerando su esquema y supuestos que hayan realizado(siempre y cuando estos últimos sean válidos/lógicos)

**Comment by Jesusdelgad** [comment]
Gracias!
