### ISSUE TITLE
Ayudantía 1

### ISSUE THREAD

**Issue by AgustinAraya** [IIC2413/Syllabus-2022-1#6]
Hola, ¿van a subir la ayudantía 1?

**Comment by Kevinnevik** [comment]
[Guía_Solución_2021_1.pdf](https://github.com/IIC2413/Syllabus-2022-1/files/8310227/Guia_Solucion_2021_1.pdf)
[Pauta_C1_BD_2021_2.pdf](https://github.com/IIC2413/Syllabus-2022-1/files/8310228/Pauta_C1_BD_2021_2.pdf)

Aun no tengo permiso para editar el repositorio pero te dejo las soluciones a dos guías.
