### ISSUE TITLE
[Entrega 1] Duda consulta 2 grupo par

### ISSUE THREAD

**Issue by AgustinAraya** [IIC2413/Syllabus-2022-1#60]
En la consulta mínima número 2 para los grupos pares se pide; "Muestre todos los vuelos que no fueron planificados por alguna compañía aérea", sin embargo en la descripción de los vuelos, se dice que estos solo se pueden solicitar por compañías aéreas... ¿Esta mal el enunciado o simplemente la consulta debe ser siempre vacía?

**Comment by matiastoro** [comment]
Deberían ser los FPL que no fueron planificados por alguna compaía aérea.
