### ISSUE TITLE
Comando tree servidor

### ISSUE THREAD

**Issue by Jesusdelgad** [IIC2413/Syllabus-2022-1#61]
Hola no me deja utilizar tree, y utilizo los comandos que me dice para instalarlo pero no pasa nada y también lo intente con el comando de " sudo apt-get install tree" pero me tira errores en todas.
![image](https://user-images.githubusercontent.com/80914510/161404044-6db56ae4-8376-4a3c-b1a4-f86d5b71f088.png)

**Comment by arpincheira** [comment]
Hola, efectivamente no se encuentra el comando tree y este no es relevante para la entrega, si bien no ocupa mucho espacio es mejor utilizar los recursos del servidor en comandos de mayor relevancia. Conversaré con los profesores para analizar su adición al servidor. Saludos

**Comment by Dafnemami** [comment]
Solo para saber, para qué sirve se comando?

**Comment by Jesusdelgad** [comment]
Es un comando de terminal que te hace ver tus rutas de la siguiente manera:
![image](https://user-images.githubusercontent.com/80914510/161669005-64d9a62e-da2e-4b88-a7d8-18280001534d.png)
