### ISSUE TITLE
[Entrega 1]Uso de ID

### ISSUE THREAD

**Issue by CristobalPerez-Cotapos** [IIC2413/Syllabus-2022-1#62]
Hola!! haciendo el esquema nos surgió una duda de su agregar un ID en tablas como la de Aeronaves ¿podemos agregar un ID en las tablas que encontremos necesario? de ser así ¿podemos referenciar al ID de la aeronave en vez de su nombre en otras tablas como la tabla de Vuelos?

**Comment by arpincheira** [comment]
Se puede añadir ID's si lo consideran necesario pero les recomiendo que en la consultas muestren el ID(que sería único) en conjunto a otro atributo significativo, como el nombre y el código internacional único (por ejemplo).
