### ISSUE TITLE
Clave del servidor

### ISSUE THREAD

**Issue by ebenstom** [IIC2413/Syllabus-2022-1#63]
Hola, al meterme al servidor me pide la clave, pero no es el número de grupo. Ni yo ni mi compañero la cambiamos, que podemos hacer?

**Comment by arpincheira** [comment]
Hola, estás probando con grupoXX o solo con XX (tu número de grupo)?

**Comment by ebenstom** [comment]
Hola! estaba probando solo con el número, gracias por el tip.
