### ISSUE TITLE
Duda respecto a la base de datos

### ISSUE THREAD

**Issue by sebacarrascop** [IIC2413/Syllabus-2022-1#64]
Con mi compañero tenemos la duda si la base de datos (CSV) con la que tenemos que probar si las consultas funcionan la tenemos que crear nosotros o se encuentra en alguna parte, ya que no la hemos podido ver y no hemos leido nada que hable sobre eso. Gracias!

**Comment by Daniel-SebastianGaete** [comment]
Los datos deben ser cargados por ustedes de manera tal que todas las consultas entreguen al menos un resultado. En ese contexto, tienen la opción (fuertemente recomendada por mí) de cargarlos mediante un CSV, pero también lo pueden hacer en el mismo Postgres usando los comandos de SQL. La referencia está en los dos últimos puntos de la sección **Formato de entrega y fecha** del enunciado.
Saludos

**Comment by Dafnemami** [comment]
el csv se debe subir al servidor o se puede leer desde el pc con la ruta relativa adecuada?
