### ISSUE TITLE
Guía 1 - f 

### ISSUE THREAD

**Issue by XRLCaro** [IIC2413/Syllabus-2022-1#7]
Hola!

Quisiera consultar si la siguiente forma para f ) de la guía 1 es equivalente a la respuesta que sale en la pauta:
En vez de poner "Jugador -", poner como condición "nick != Jugador.nick_creador" para el join de Jugador y Sala

De antemano muchas gracias! Saludos

**Comment by DomagojVrgoc** [comment]
Hola.

No, esto no resultará en el resultado correcto.

Al poner la condición "nick != Jugador.nick_creador" tu consulta va a construr tuplas que corresponden a pares (jugador,sala), dónde este jugador no creó este sala.
