### ISSUE TITLE
Entrega de los archivos con git hub

### ISSUE THREAD

**Issue by antoniablanco** [IIC2413/Syllabus-2022-1#71]
Hola, buenos dias.
En principio sin darme cuenta uni al servidor una branch del repositorio de github que tenemos como grupo. Por lo cual hoy uni esa branch a la original, dado que al intentar realizar un cambio en mi computador este se realizaba en la original y no la nueva creada. El problema es que al intentar visualizar estos cambios en el servidor me entrega esta respuesta: 
"Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched." 
Por lo cual queria saber si es que saben como solucionarlo para poder realizar la entrega. O si es que hay alguna forma de desconectar la union git-servidor, para crear una nueva.
Muchas gracias

**Comment by arpincheira** [comment]
Hola, a decir verdad existen muchas maneras de "solucionar" lo que solicitas, te recomiendo ver [este link](https://stackoverflow.com/questions/36984371/your-configuration-specifies-to-merge-with-the-branch-name-from-the-remote-bu) por si es de utilidad
