### ISSUE TITLE
Git full desde el server

### ISSUE THREAD

**Issue by simonmb12** [IIC2413/Syllabus-2022-1#72]
Hola,
Si tengo la carpeta Entrega1 con el pdf pedido en mi repositorio de GitHub. Para hacer el git pull desde le server y cargar dicha carpeta, debo hacerlo desde grupoxxx@codd.ing.puc.cl o después de haber ingresado psql y estar en grupoxxx??

**Comment by arpincheira** [comment]
Desde grupoXX@codd.ing.puc.cl
