### ISSUE TITLE
Grupo impar consulta 6 dinero gastado

### ISSUE THREAD

**Issue by Gjescalante** [IIC2413/Syllabus-2022-1#73]
Hola! tenemos una duda pues según el enunciado un pasajero puede comprar varios tickets, pero cada ticket va asociado a una persona, esto nos da a entender que hay pasajeros que no gastaron en su pasaje. 

Y como la pregunta 6 pregunta por el monto gastado en reservas por cada pasajero nos queda la duda. ¿Es necesario llevar un registro de qué usuario en particular hizo la reserva, o se puede asumir que si un usuario tiene la reserva a su nombre, el mismo la compró?

**Comment by matiastoro** [comment]
La idea es que guarden quien hizo la reserva

**Comment by Dafnemami** [comment]
Con ánimo de clarificar, lo anterior que mencionas implica que el monto gastado, por cada usuario en reservas, se refiere solamente a quienes hacen las reservas?

**Comment by matiastoro** [comment]
Si
