### ISSUE TITLE
Duda sobre codigo de vuelo

### ISSUE THREAD

**Issue by drcid98** [IIC2413/Syllabus-2022-1#74]
El código de vuelo es único? lo pregunto ya que si este solo consiste de el código de la compañía + 3 números, la cantidad de vuelos que se pueden realizar sería bastante chica. En caso de que NO sea único (como hasta este punto he asumido), está bien que para las request pedidas se entregue un id de vuelo y no su código?

**Comment by Daniel-SebastianGaete** [comment]
El código no es único. Como referencia, generalmente las aerolíneas le entregan el mismo código a dos vuelos que ocurren en distintos días pero en el mismo horario.
En teoría no debiera haber problema en que tus consultas muestren id en vez de código pero este último se puede aprovechar para que los resultados se vean más ordenados.
