### ISSUE TITLE
Database Entrega

### ISSUE THREAD

**Issue by Gau04** [IIC2413/Syllabus-2022-1#75]
Hola! Con mi compañero nos acabamos de dar cuenta que estuvimos trabajando todo el rato en la base de datos grupo79 en vez de grupo79e1, hay alguna manera de solucionar esto sin tener que agregar las tablas en la otra base de datos una por una de nuevo? :(

**Comment by arpincheira** [comment]
Hola, me podrías confirmar si es que ahora grupo79e1 posee toda la información de grupo79?

**Comment by Gau04** [comment]
Siii esta toda la informacion, muchas gracias!!!!

**Comment by VicenteSaldana** [comment]
Holaa, a nosotros nos pasó lo mismo :( 
Nos podrían ayudar? Somo el grupo 94

**Comment by arpincheira** [comment]
Hola, lamento la demora, pueden verificar si es que están?

**Comment by VicenteSaldana** [comment]
Siii, muchas graciaas <3
