### ISSUE TITLE
Vuelos no planificados por alguna compañia aérea

### ISSUE THREAD

**Issue by josetomasacuna** [IIC2413/Syllabus-2022-1#77]
En el apartado de vuelos (grupos pares) dice "Un vuelo representa una propuesta de viaje entre dos aeródromos enviado por una compañía aérea...". Mi duda es: Si un vuelo solo puede ser ingresado por una compañía aérea, entonces cuando se pide mostrar todos los vuelos que no fueron planificados por alguna compañía aérea, se está hablando de flight plan y no de un vuelo?

**Comment by josetomasacuna** [comment]
Por otro lado, cuando se pide muestre todos los vuelos con origen 'SCEL' debemos remitirnos exclusivamente a vuelos ( es decir, propuesta de viaje... con un mes de antelación). O se deben considerar también los FLP

**Comment by matiastoro** [comment]
1.- Correcto se esta hablando del flight plan.
2.- Puede ser ambos

**Comment by josetomasacuna** [comment]
para la 2.- Puedo suponer que la tabla FPL abarca a la tabla vuelos? Es decir, que todos los vuelos tienen asociado un FPL

**Comment by josetomasacuna** [comment]
A que se refiere exactamente con puede ser? Me explico, si busco exclusivamente en el conjunto vuelo vuelos que tengan como origen SCEL, estos vuelos pueden estar asociados a un plan de vuelo, por lo que técnicamente incluye un vuelo y un plan de vuelo. O más fácil, tengo que buscar vuelos con origen SCEL y por separado chequear el conjunto FPL. O solo tengo que chequear uno de los conjuntos, el cual, por la forma que están organizados puede tener elementos en común?

**Comment by matiastoro** [comment]
Puedes elegir cualquiera de las dos opciones. Te sugiero devolver los FPL con origen SCEL, anotando los supuestos en ma entrega.
