### ISSUE TITLE
[Entrega 1] Duda archivos en servidor

### ISSUE THREAD

**Issue by aboehmg** [IIC2413/Syllabus-2022-1#79]
Hola, 
Tuve que vincular otro repositorio a mi servidor y al momento de borrar el antiguo leí mal la otra issue y borré más archivos de los necesarios. En particular, los archivos ".bash_logout", ".bashrc", ".profile" los borré y no aparecieron de nuevo. Además, ya no aparecen con colores. ¿Qué puedo hacer para solucionar mi situación?
¡Saludos!

**Comment by barbaraureta** [comment]
Hola, ya nos volvieron los archivos pero no los colores
Muchas gracias y perdón el inconveniente

**Comment by arpincheira** [comment]
Podrías corroborar ahora?

**Comment by barbaraureta** [comment]
Ahora sí está todo bien. Muchas gracias!
