### ISSUE TITLE
[Entrega 1] consulta 5 grupo impar

### ISSUE THREAD

**Issue by nico-sv** [IIC2413/Syllabus-2022-1#80]
Hola! cuando me dicen que muestre las rutas más usadas, se refieren a que hay que mostrar el uso de todas las rutas en orden descendiente o solamente la o las rutas mas usadas (en caso de que haya un empate)?

**Comment by matiastoro** [comment]
Ordenadas por orden descendiente.

**Comment by nico-sv** [comment]
gracias!
