### ISSUE TITLE
Consultas 5 y 6 grupos pares.

### ISSUE THREAD

**Issue by Manrrolo** [IIC2413/Syllabus-2022-1#83]
Hola! Para las consultas 5 y 6 de los grupos pares tenemos la duda si todos los vuelos son FPL. O si debemos agregar los atributos 'hora de llegada', 'hora de salida' y 'número de pasajeros' a la tabla de vuelo para hacer las consultas mencionadas. 
Gracias de antemano.

**Comment by Daniel-SebastianGaete** [comment]
No todos los vuelos son FPL pero no debes considerar aquellos que no para la consulta 6 porque no tienen pasajeros. Para la 5, ambos tienen hora de llegada y salida.
