### ISSUE TITLE
Qué tablas rellenar y cuáles no (y un poco más)

### ISSUE THREAD

**Issue by vcrb18** [IIC2413/Syllabus-2022-1#84]
Tengo la duda, debería llenar sólamente las tablas que serían utilizadas para las primeras tres consultas? Así lo entiendo yo al menos del enunciado.
Lo entendí mal y debiera llenar todas las tablas?

**Comment by vcrb18** [comment]
Para mí caso que soy grupo par, esto sería llenar solo las tablas de FPL y de vuelos.
Y si por ejemplo lo hubiera entendido bien, debería llenar las tablas a las que hago alusión como atributos en la tabla?
Me explico, si mi tabla vuelos tiene un atributo id del aeródromo que sería el código ICAO, debería llenar con datos entonces mi tabla de "aeródromo"?
Espero que se entienda :S

**Comment by vcrb18** [comment]
Perdón que siga en este issue.
Si un FPL es por ejemplo rechazado, significa que no tendrá velocidad, altitud, etc.
Depende de mí como relleno esos datos? Como por ejemplo con "0" o con "-"

**Comment by arpincheira** [comment]
Hola, lamento mucho la demora en contestar. La idea es que rellenen solo las tablas que sirvan para que, dado su esquema, se puedan contestar todas las consultas solicitadas. Ahora, si en tu caso solo son 2 tablas eso está bien, en la siguiente entrega se va ahondar un poco más en cómo modificar su esquema inicial con el objetivo de que estén los datos normalizados. 

Con respecto a tu segunda pregunta, si no se solicitan los datos de la tabla aeródromo entonces no es necesario que la crees dado que reverenciarla con el id está bien.

Contestando a la tercera pregunta, por ahora depende de ti como rellenas dichos datos, de todas formas recomiendo seleccionar valores que se puedan reconocer como vacíos o explicar en el reporte los supuestos que hiciste para designar los "0" y "-" como referentes para indicar que esos valores no están.
