### ISSUE TITLE
Duda archivos csv

### ISSUE THREAD

**Issue by mhrobles** [IIC2413/Syllabus-2022-1#85]
para crear las tablas con la base de datos (en mi caso .csv) tengo que tener esos archivos, por lo que hay problema si pongo la base de datos dentro del github? o no está permitido?

**Comment by vcrb18** [comment]
Me sumo a la duda, tengo entendido que el csv debe estar en el servidor para poder agregarlo a mis tablas.
(No lo he intentado aún, pero eso dice stackoverflow).
Hay algún problema con eso?
