### ISSUE TITLE
Duda Consultas Grupo Impar

### ISSUE THREAD

**Issue by robertoorrego** [IIC2413/Syllabus-2022-1#86]
Hola! No me queda claro que consultas se deben hacer en psql y cuales en álgebra relacional.

Gracias!

**Comment by arpincheira** [comment]
Hola, son las primeras 3 que van tanto el álgebra relacional como en psql.
En su caso serían:
<img width="717" alt="Captura de Pantalla 2022-04-07 a la(s) 17 44 26" src="https://user-images.githubusercontent.com/37157550/162325037-5af2fef9-77f8-4594-87b0-3f133a1344ed.png">

**Comment by TonioElbuey** [comment]
Hola! Pero en el README de la Entrega 1 hay este mensaje :

```
#  Modificaciones

Fecha           | Hora      |  Modificación
---------------- |--------- |--------------- 
29-03-2022       | 15:00    | Se cambian de  orden las consultas 3 y 5 de los grupos impares
```

Entonces no debemos hacer la quinta?

**Comment by arpincheira** [comment]
Hola, lo que sucede es que eso es un registro que indica el día y la hora de la modificación que se hizo al enunciado en conjunto a una explicación del cambio realizado, es decir, la pregunta 3 del enunciado que puedes descargar ahora es la pregunta 5 del enunciado original, esto con el objetivo de corregir un error por el cual no era posible hacer dicha consulta en álgebra relacional.(las consultas de la foto son las correctas)
