### ISSUE TITLE
Problema para acceder al servidor

### ISSUE THREAD

**Issue by javialf123** [IIC2413/Syllabus-2022-1#87]
Hola, cuando trato de acceder al servidor me aparece el siguiente mensaje:

The authenticity of host 'codd.ing.puc.cl (146.155.13.72)' can't be established.
ED25519 key fingerprint is SHA256:05UiO9G6QtU3WxIgu5ZgaRD03AkLFs6TL7IV0gg34Xc.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])?
Host key verification failed.

no se que puedo estar haciendo mal. el comando ingresado es:

ssh grupo60@codd.ing.puc.cl

**Comment by arpincheira** [comment]
Creo que eso se puede solucionar con el comando `ssh-key gen -f "dirección de la carpeta know_host de tu computadora" -R "codd.ing.puc.cl"`

**Comment by javialf123** [comment]
cual es la carpeta know_host? donde estoy parado en el minuto de ejecutar?
