### ISSUE TITLE
Poblar tablas con CSV

### ISSUE THREAD

**Issue by clangoi** [IIC2413/Syllabus-2022-1#88]
Hola, estamos tratando de poblar las tablas de la base de datos con un csv. Ya creamos las tablas pero al momento de escribir en consola 
`\COPY aerodromo from '/Entrega1/CSV/Aerodromo.csv' DELIMITER ',' CSV HEADER;`
esta arroja 
`/Entrega1/CSV/Aerodromo.csv: No such file or directory`
siendo que los archivos se encuentran en la carpeta CSV que está en Entrega1

**Comment by arpincheira** [comment]
Hola, eso es porque los path son: `/home/grupoXX/Entrega1/CSV/Aerodromo.csv` o `./Entrega1/CSV/Aerodromo.csv`, ya que sin el `.` inicial lo que están haciendo es usar un path absoluto y la dirección que dan es la de un path relativo.

**Comment by clangoi** [comment]
Hola, intenté de ambas formas, y me sigue apareciendo lo mismo :(
![image](https://user-images.githubusercontent.com/53914794/162517796-fe2e2b46-f71d-496c-bc70-04d14a12f52c.png)
