### ISSUE TITLE
Pregunta 3 Control 1

### ISSUE THREAD

**Issue by gecoli** [IIC2413/Syllabus-2022-1#9]
Buenas, quisiera especificar este enunciado

![image](https://user-images.githubusercontent.com/62023237/159348598-140974ad-952b-4329-a9f5-8d4977689be7.png)

Me piden que verifique sólo si está en la tabla **Personal**, no en la **TrabajaEn**, ¿cierto? 

De antemano, muchas gracias

**Comment by matiastoro** [comment]
Los capitanes que no estan en la tabla Personal
