### ISSUE TITLE
Duda tripulacion 

### ISSUE THREAD

**Issue by vpaivag** [IIC2413/Syllabus-2022-1#90]
Hola tengo una duda en relación a la tripulación de cabina en la parte de grupos impares. Tripulacion de cabina es un grupo de personas? Si ese es el caso, un vuelo incluye una tripulacion o muchas tripulaciones?

**Comment by arpincheira** [comment]
Hola, la tripulación en si está compuesta por un grupo de personas que poseen cargos correspondientes a eso. En el caso de un vuelo, este posee un conjunto de personas que componen finalmente a la tripulación de este.
