### ISSUE TITLE
[Entrega 1] Dudas respecto a Tickets

### ISSUE THREAD

**Issue by ElTioAndresCabezas** [IIC2413/Syllabus-2022-1#91]
¡Saludos!
Con respecto al funcionamiento de los tickets, ¿estos se generan únicamente cuando se compra un pasaje de avión, o pueden existir de antes y ser asignados a un pasajero una vez sean comprados? Si lo ultimo es el caso, ¿estos deben estar generados para todos los status del vuelo o se generan solo cuando el status es *"publicado"*?

¡Gracias de antemano!

**Comment by arpincheira** [comment]
En lo que respecta a esta entrega ambos modelos son correctos, es decir, que los tickets en si se generen al ser publicado un vuelo o que estos se generen cuando una persona los compra. Ahora, en lo personal creo que el segundo acercamiento puede ser el mejor. En lo que respecta a tu segunda pregunta, puedes hacer el supuesto de que estos se generan cuando el status del vuelo es "publicado" y mencionar esto en el informe(en un apartado de supuestos/consideraciones usadas para la creación del esquema)
