### ISSUE TITLE
Ruta y puntos

### ISSUE THREAD

**Issue by AmeliaIacobelli** [IIC2413/Syllabus-2022-1#93]
Hola! no entiendo bien a que se refiere con nombre y puntos en la ruta.
Podemos asumir que es solo punto de salida y de llegada? Podemos relacionar estos puntos con ciudades?
Tampoco entiendo el concepto de lista de puntos, esta lista la puedo pasar a tabla? yo defino el largo?

Gracias!

**Comment by matiastoro** [comment]
Una ruta podria ser
DONTI4B DONTI UQ802 KUGAP UQ802 REPUK REPUK2B
Donde cada uno de esas palabras corresponden a puntos con su latitud y longitud. Además esos mismos puntos pueden usarse en otras rutas.

**Comment by conicorreag** [comment]
Hola! respecto a esto, todavía no me queda claro cuántos puntos deben haber en una ruta. No es solo el de salida y el de llegada? los otros serian escalas? o lugares por los que pasa volando?
Y lo otro, los nombres que pusiste, son el nombre más la coordenada? es decir, en UQ802, UQ es el nombre y 80 la latitud y 2 la longitud por ejemplo?

**Comment by Dafnemami** [comment]
Me sumo también a la pregunta, por qué considerar más de dos puntos si son rutas *sin escalas*? Ya que en principio podríamos considerar una cantidad numerable pero muy grande para la cantidad de puntos asociados a una ruta, porque no hay una definición al respecto.

**Comment by matiastoro** [comment]
Pueden haber muchos puntos en una ruta. Los puntos no tienen nada que ver con las escalas. Un vuelo con 2 escalas son dos FPL.
Los puntos soncoordenadas geograficas con nombre, porque indica por donde va a volar el avion.
Por ejemplo DONTI podria representar el punto geografico  70º10'11''S  044º10'11''W. Estas coordenadas no van en la ruta, porque son siempre las mismas. Solo se usa el nombre.
