### ISSUE TITLE
Atributos a seleccionar en consultas de grupos impares

### ISSUE THREAD

**Issue by isufan** [IIC2413/Syllabus-2022-1#94]
Hola! En las 3 primeras consultas de los grupos impares, ¿es posible seleccionar solo algunos atributos de los vuelos que cumplen las condiciones (como código y fecha) en vez de seleccionarlos todos? Gracias de antemano.

**Comment by Daniel-SebastianGaete** [comment]
La esencia de la consulta no debiera cambiar si cambias la cantidad de atributos mostrados, así que debiera dar lo mismo mientras muestres los relevantes para dicha consulta
