### ISSUE TITLE
Subir informe desde la terminal

### ISSUE THREAD

**Issue by PedroGiesen** [IIC2413/Syllabus-2022-1#95]
Estoy tratando de subir el informe desde la terminal, pero al escribir rl comando: 
scp InformeE1.pdf grupoXX@codd.ing.puc.cl:~/Entrega1/Informe.pdf pero me tira error, InformeE1.pdf: No such file or directory
No se si el problema es en que carpeta estoy o el codigo que tengo que ingresar

**Comment by arpincheira** [comment]
Hola, desdee donde estás ejecutando dicho comando?

**Comment by PedroGiesen** [comment]
Desde la terminal del computador. Probé antes de entrar al servidor entrar a la carpeta del archivo, hacerlo desde el inicio y todo

**Comment by arpincheira** [comment]
Es muy raro pues acabo de probar textualmente el comando que mencionas y funcionó correctamente, aquí mando unos screenshots detallando el paso a paso del proceso:

En primer lugar verifico los contenidos de mi usuario de prueba en el servidor (grupo130 en este caso):
<img width="568" alt="Captura de Pantalla 2022-04-08 a la(s) 21 46 09" src="https://user-images.githubusercontent.com/37157550/162551844-248c6656-9d12-41e9-be77-edb23f940916.png">

Luego creo una carpeta denominada test y, al interior de esta, un archivo denominado hola2.txt, luego verifico su existencia(uso nano envés de touch pero con el segundo también debería funcionar)

<img width="569" alt="Captura de Pantalla 2022-04-08 a la(s) 21 43 50" src="https://user-images.githubusercontent.com/37157550/162551891-d84e503b-ef60-43c6-88a9-7ac8c9955db5.png">

Foto de la carpeta con su único archivo
<img width="720" alt="Captura de Pantalla 2022-04-08 a la(s) 21 44 02" src="https://user-images.githubusercontent.com/37157550/162551900-3507bb37-f0c5-45b5-b726-0194962cb680.png">

Dentro de la carpeta llamo al comando que mencionas:

<img width="568" alt="Captura de Pantalla 2022-04-08 a la(s) 21 44 32" src="https://user-images.githubusercontent.com/37157550/162551912-f9806ad3-76e2-4987-91c5-9edafbee01cb.png">

Verifico que el archivo esté en el servidor:
<img width="568" alt="Captura de Pantalla 2022-04-08 a la(s) 21 46 29" src="https://user-images.githubusercontent.com/37157550/162551925-b0384cc9-d492-4816-979b-41fda2a4f7e2.png">
